/-
# T-GEN keystone bridge: π₁-generation ⟹ analytic loops generate H₁ (TGEN lane)

The single load-bearing reduction for the named topological residual
**T-GEN** (`AnalyticLoopsGenerateH1`, `H1Composite.lean`): it converts any
*group-theoretic* generation statement about `FundamentalGroup X x₀` into the
*module-theoretic* spanning statement T-GEN asks for.

## The reduction

`H1 X x₀ = Additive (Abelianization (FundamentalGroup X x₀))` and
`loopToHomology γ = Additive.ofMul (Abelianization.of (fromPath ⟦loopToPath γ⟧))`.
So an analytic loop's H₁ class is *literally* the abelianized π₁ class of its
underlying path. Hence:

* **(P)** — the analytic-loop classes generate `π₁(X, x₀)` as a group
  (`pi1AnalyticClasses x₀ = ⊤`) — implies
* **T-GEN** — the analytic-loop classes ℤ-span `H1 X x₀`
  (`AnalyticLoopsGenerateH1 x₀`).

The proof is Mathlib-only abelianization algebra: by
`Subgroup.closure_induction` over (P)'s generating set, every π₁ class lands
in the additive subgroup `loopHomologyClasses x₀` of analytic-loop H₁ classes
(`HomologyGeneration.lean`), which is closed under `+`, `-`, `0`; the
generators map in by definition. Then `coe_span_range_loopToHomology` upgrades
"every class is a loop class" to "the ℤ-span is `⊤`".

`analyticLoopsGenerateH1_of_pi1_closure` is rung **K0** of `TGEN_ROUTE.md`.
It is the reusable lemma every downstream π₁-generation result (family-level
via the branched-cover lasso lift, or general-X) feeds into to obtain T-GEN.

No axiom is introduced; nothing here depends on `AX_PeriodCycleBasis`.
-/
import Jacobians.RiemannSurface.H1Composite

namespace Jacobians.RiemannSurface

open scoped Manifold Topology
open scoped ContDiff
open Jacobians.Axioms (loopToHomology loopToPath)

noncomputable section

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold 𝓘(ℂ) ω X]
variable {x₀ : X}

local notation "Qmk" => Path.Homotopic.Quotient.mk

/-- The π₁ class of an analytic loop based at `x₀`: the `FundamentalGroup`
element of the loop's underlying path. `loopToHomology` is exactly the
abelianization of this. -/
def loopToPi1 (γ : AnalyticLoop X x₀) : FundamentalGroup X x₀ :=
  FundamentalGroup.fromPath (Qmk (loopToPath γ))

@[simp]
theorem loopToHomology_eq_ofMul_of_loopToPi1 (γ : AnalyticLoop X x₀) :
    loopToHomology γ = Additive.ofMul (Abelianization.of (loopToPi1 γ)) := by
  rw [loopToPi1, loopToHomology]

/-- The subgroup of `FundamentalGroup X x₀` generated by the classes of
analytic loops. Property **(P)** of `TGEN_ROUTE.md` is
`pi1AnalyticClasses x₀ = ⊤`. -/
def pi1AnalyticClasses (x₀ : X) : Subgroup (FundamentalGroup X x₀) :=
  Subgroup.closure (Set.range (loopToPi1 : AnalyticLoop X x₀ → FundamentalGroup X x₀))

/-- **K0 — the keystone bridge (membership form).** If the π₁ class of every
analytic loop generates a subgroup containing `g`, then the abelianized,
additive class of `g` is the H₁ class of a single analytic loop. The induction
runs over `Subgroup.closure`, landing each step in the additive subgroup
`loopHomologyClasses x₀` of analytic-loop H₁ classes. -/
theorem exists_loop_of_mem_pi1AnalyticClasses {x₀ : X}
    {g : FundamentalGroup X x₀} (hg : g ∈ pi1AnalyticClasses x₀) :
    ∃ γ : AnalyticLoop X x₀,
      loopToHomology γ = Additive.ofMul (Abelianization.of g) := by
  -- The target set "is a single analytic-loop H₁ class" = carrier of the
  -- additive subgroup `loopHomologyClasses x₀`, pulled back along
  -- `g ↦ ofMul (Abelianization.of g)`.
  have key : Additive.ofMul (Abelianization.of g) ∈ loopHomologyClasses x₀ := by
    refine Subgroup.closure_induction
      (k := Set.range (loopToPi1 : AnalyticLoop X x₀ → FundamentalGroup X x₀))
      (p := fun a _ => Additive.ofMul (Abelianization.of a) ∈ loopHomologyClasses x₀)
      ?mem ?one ?mul ?inv hg
    case mem =>
      rintro _ ⟨γ, rfl⟩
      exact ⟨γ, (loopToHomology_eq_ofMul_of_loopToPi1 γ).symm⟩
    case one =>
      simp only [map_one]
      exact (loopHomologyClasses x₀).zero_mem
    case mul =>
      intro a b _ _ ha hb
      have : Additive.ofMul (Abelianization.of (a * b))
          = Additive.ofMul (Abelianization.of a)
            + Additive.ofMul (Abelianization.of b) := by
        rw [map_mul]; rfl
      rw [this]
      exact (loopHomologyClasses x₀).add_mem ha hb
    case inv =>
      intro a _ ha
      have : Additive.ofMul (Abelianization.of a⁻¹)
          = -(Additive.ofMul (Abelianization.of a)) := by
        rw [map_inv]; rfl
      rw [this]
      exact (loopHomologyClasses x₀).neg_mem ha
  obtain ⟨γ, hγ⟩ := key
  exact ⟨γ, hγ⟩

/-- **K0 — the keystone bridge.** If the analytic-loop classes generate
`FundamentalGroup X x₀` as a group (property (P)), then they ℤ-span
`H1 X x₀`: the named topological residual **T-GEN**
(`AnalyticLoopsGenerateH1`). This is the reusable reduction that every
π₁-generation result — family-level (branched-cover lasso lift) or general-X —
feeds into. Axiom-free; no `AX_PeriodCycleBasis`. -/
theorem analyticLoopsGenerateH1_of_pi1_closure {x₀ : X}
    (hP : pi1AnalyticClasses x₀ = ⊤) :
    AnalyticLoopsGenerateH1 x₀ := by
  -- T-GEN ⟺ every H₁ class is a single analytic-loop class, via
  -- `coe_span_range_loopToHomology` (span = range of `loopToHomology`).
  rw [AnalyticLoopsGenerateH1, Submodule.eq_top_iff']
  intro v
  rw [← SetLike.mem_coe, coe_span_range_loopToHomology]
  -- Every `v : H1` is `ofMul (Abelianization.of g)` for some `g : π₁`.
  obtain ⟨m, rfl⟩ := (Additive.ofMul (α := Abelianization (FundamentalGroup X x₀))).surjective v
  induction m using QuotientGroup.induction_on with
  | _ g =>
    have hg : g ∈ pi1AnalyticClasses x₀ := hP ▸ Subgroup.mem_top g
    exact exists_loop_of_mem_pi1AnalyticClasses hg

/-- **K0, family form.** If a finite family `γ : Fin n → AnalyticLoop X x₀`
of analytic loops has π₁ classes generating `FundamentalGroup X x₀`, then
T-GEN holds. This is the shape a branched-cover / lasso-lift argument
delivers its output in (a finite generating set of explicit analytic loops).
-/
theorem analyticLoopsGenerateH1_of_finite_pi1_generators {x₀ : X} {n : ℕ}
    (γ : Fin n → AnalyticLoop X x₀)
    (hgen : Subgroup.closure (Set.range fun i => loopToPi1 (γ i)) = ⊤) :
    AnalyticLoopsGenerateH1 x₀ := by
  refine analyticLoopsGenerateH1_of_pi1_closure ?_
  -- The finite family's classes are a subset of all analytic-loop classes,
  -- so their closure (already ⊤) is ≤ `pi1AnalyticClasses`.
  refine top_le_iff.mp ?_
  rw [← hgen]
  exact Subgroup.closure_mono
    (Set.range_subset_iff.mpr fun i => ⟨γ i, rfl⟩)

/-- **K0, surjection form.** If *every* π₁ class is the class of some analytic
loop (the map `loopToPi1` is surjective onto `FundamentalGroup X x₀`), then
T-GEN holds. The strongest, easiest-to-supply form. -/
theorem analyticLoopsGenerateH1_of_loopToPi1_surjective {x₀ : X}
    (hsurj : Function.Surjective (loopToPi1 : AnalyticLoop X x₀ → FundamentalGroup X x₀)) :
    AnalyticLoopsGenerateH1 x₀ := by
  refine analyticLoopsGenerateH1_of_pi1_closure ?_
  rw [pi1AnalyticClasses, hsurj.range_eq, Subgroup.closure_univ]

end

end Jacobians.RiemannSurface
