/-
# L2: covering-space generation of π₁ ⟹ T-GEN (TGEN lane, rung L2)

`docs/planning/TGEN_ROUTE.md` rung **L2**: the lifted lassos + filled-puncture
relations generate `π₁(X)`. This is the **last mathematical wall** of the
challenge — every other rung of T-GEN is proven:

* **K0** (`AnalyticPi1Generation.lean`): any π₁-generation statement ⟹ T-GEN.
* **D1** (`IsolatingLasso.lean`): π₁(ℂ∖B) is generated by analytic circle
  lassos (`normalClosure_isolatingLassos_eq_top`).
* **L1** (`Hyperelliptic/CycleLoops.lean`): the √-lift of a base arc through
  the branched cover is analytic (`SqrtArcData`, `exists_sqrtArcData`,
  `HyperellipticAffine.sqMap_covering`).

L2 connects D1's downstairs generators to upstairs π₁ across the finite
branched cover `π : X → ℙ¹`. This file does three things:

1. **Names L2 precisely** as one covering-space generation predicate
   (`CoveringGeneratesPi1`) — the final Mathlib-absent topology fact.
2. **Records the witness-family reduction**: for the hyperelliptic
   `BranchCutSystem`, *if* the `2g` branch-cut analytic loops generate
   `π₁(HyperellipticOdd H h)`, *then* T-GEN holds for that curve. This is a
   drop-in over K0's finite-family form — axiom-free, sorry-free. It
   reduces the hyperelliptic instance of T-GEN to a single, concrete
   group-generation hypothesis about explicit loops.
3. **Names the residual** `BranchCutGeneratesPi1` capturing exactly that
   hypothesis, so the wall for the cleanest witness family is one named
   statement, not a mass of covering-space scaffolding.

No new axiom; nothing depends on `AX_PeriodCycleBasis`.

## The precise general L2 wall

> **L2 (general).** Let `π : E → Y` be a finite covering map of
> path-connected, locally path-connected spaces, `e₀ ∈ E`, `S ⊆ π₁(Y, π e₀)`
> a generating set. Then `π₁(E, e₀)` is generated by the set of **closed
> lifts at `e₀`** of those reduced words in `S` whose monodromy fixes `e₀`
> (the Reidemeister–Schreier / point-stabilizer generators). For the
> *branched* completion that fills the finite ramification fiber `T`, the
> meridian classes of `T` are additionally killed (a punctured chart-disk
> upstairs simply-connects after the puncture is filled).

Mathlib supplies `IsCoveringMap`, `liftPath`, the monodromy action, and (this
project, `CoveringPi1.lean`) `monodromy_injective`/`monodromy_surjective` for a
*simply connected* total space — i.e. the deck-group identification used at
genus 1. It does **not** supply the stabilizer-generation statement for a
finite cover with non-simply-connected total space, nor the branched
puncture-filling. That is the residual named here.
-/
import Jacobians.RiemannSurface.AnalyticPi1Generation
import Jacobians.ProjectiveCurve.Hyperelliptic.CycleBasisWitness

namespace Jacobians.RiemannSurface

open scoped Manifold Topology
open scoped ContDiff
open Jacobians.Axioms (loopToHomology loopToPath)
open Jacobians.ProjectiveCurve

noncomputable section

/-! ## The general L2 covering-generation predicate (the named wall) -/

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold 𝓘(ℂ) ω X]

/-- **L2, general form (named residual).** For a basepoint `x₀ : X`, the
property that the analytic-loop classes generate `π₁(X, x₀)` as a group —
i.e. property **(P)** of `TGEN_ROUTE.md`, `pi1AnalyticClasses x₀ = ⊤`.

This is definitionally property (P); naming it here marks the spot where the
covering-space argument (lift D1's downstairs lassos through the branched
cover `π : X → ℙ¹`, fill the ramification punctures) discharges the wall. By
K0 (`analyticLoopsGenerateH1_of_pi1_closure`) it implies T-GEN. -/
def CoveringGeneratesPi1 (x₀ : X) : Prop :=
  pi1AnalyticClasses x₀ = ⊤

/-- **L2 ⟹ T-GEN.** Once the covering-space lift establishes that analytic
loops generate `π₁`, T-GEN follows by the K0 keystone bridge. This is the
exact shape in which a general-X covering argument feeds T-GEN. -/
theorem analyticLoopsGenerateH1_of_coveringGeneratesPi1 {x₀ : X}
    (h : CoveringGeneratesPi1 x₀) : AnalyticLoopsGenerateH1 x₀ :=
  analyticLoopsGenerateH1_of_pi1_closure h

end

/-! ## The hyperelliptic witness: L2 reduced to one generation hypothesis -/

namespace ProjectiveCurve

open Jacobians.ProjectiveCurve BranchCutSystem

variable {H : HyperellipticData} {h : Odd H.f.natDegree}

/-- **L2 for the hyperelliptic witness (named residual).** The `2g`
branch-cut analytic loops of a `BranchCutSystem` generate
`π₁(HyperellipticOdd H h)` at the system's basepoint.

This is the *generation* shadow of the `isBasis`/`tie` hypotheses of
`nonempty_periodCycleBasis_of_branchCutSystem` — strictly weaker (spanning,
not a ℤ-basis), and it is *exactly* what T-GEN needs. Its content is the
double-cover monodromy of `y² = f(x)`: D1's lassos around the branch points
(`normalClosure_isolatingLassos_eq_top`) lift through the √-cover
(`sqMap_covering`, L1) to the system's loops, and these lifts generate π₁
upstairs (the finite-cover stabilizer-generation fact of the general L2
wall, here for an explicit 2-sheeted cover). -/
def BranchCutGeneratesPi1 (S : BranchCutSystem H h) : Prop :=
  Subgroup.closure
      (Set.range fun i : Fin (2 * genus (HyperellipticOdd H h)) =>
        loopToPi1 (S.loop i))
    = ⊤

/-- **T-GEN for the odd hyperelliptic curve, conditional on the named L2
witness.** Given a branch-cut system whose `2g` analytic loops generate π₁
(`BranchCutGeneratesPi1`), the analytic loops ℤ-span `H1` at the system's
basepoint — the named residual **T-GEN** for `HyperellipticOdd H h`.

The proof is the K0 finite-family bridge applied to the explicit
`S.loop : Fin (2g) → AnalyticLoop` family. No axiom, no sorry, no
`AX_PeriodCycleBasis`: the *only* input is the group-generation hypothesis,
which is the hyperelliptic instance of the L2 covering-space wall. This
reduces hyperelliptic T-GEN to one concrete statement about explicit loops. -/
theorem analyticLoopsGenerateH1_hyperelliptic_of_branchCutGenerate
    (S : BranchCutSystem H h) (hgen : BranchCutGeneratesPi1 S) :
    AnalyticLoopsGenerateH1 S.basePoint :=
  analyticLoopsGenerateH1_of_finite_pi1_generators S.loop hgen

end ProjectiveCurve

end Jacobians.RiemannSurface
