/-
# Period-lattice discreteness (B-4) and ZLattice packaging (B-5)

The lattice-geometry half of the Forster §21.4 route to
`AX_PeriodCycleBasis`, built on the B-3 non-degeneracy engine
(`PeriodNondegeneracy.lean`).

The Forster-model period lattice is `loopPeriodLattice x₀ b`: the ℤ-span of
the coordinate period vectors of **all** closed analytic loops based at
`x₀`. No chosen cycle basis and no axiom enter the definition.

* **Spanning (from B-3, axiom-free).**
  `span_real_loopPeriodLattice_eq_top`: the lattice ℝ-spans `ℂ^g`, by
  transporting `span_loopPeriodFunctional_eq_top` through the dual
  coordinate equivalence.
* **Named hypothesis (the honest residual).**
  `PeriodGeneratingLoops x₀ b γs`: a `Fin (2g)`-indexed family of analytic
  loops whose period vectors ℤ-generate every loop's period vector. This is
  the lattice shadow of "`H₁(X, ℤ)` is generated by `2g` loop classes" —
  the topological rank count (Forster §21.4b context). It carries **no**
  Hodge-theoretic content (no R1/R2).
* **B-4 (discreteness).** `PeriodGeneratingLoops.discreteTopology`: `2g`
  generators of a lattice that ℝ-spans the `2g`-real-dimensional `ℂ^g` form
  an ℝ-basis (`basisOfTopLeSpanOfCardEqFinrank`), so the lattice is the
  ℤ-span of an ℝ-basis and Mathlib's `ZSpan` instances give discreteness.
* **B-5 (ZLattice packaging).** `isZLattice_loopPeriodLattice` (needs only
  the B-3 spanning, not the named hypothesis), a `Fin (2g)`-indexed ℤ-basis
  of the lattice (`PeriodGeneratingLoops.exists_basis`), and
  `PeriodGeneratingLoops.finrank_eq` (`finrank ℤ = 2g`).

Design: `docs/planning/B_LANE_PROGRESS.log` (2026-06-11 session);
`docs/planning/KIROV_ROUTE_IDEAS.md` §5 (B-1…B-5 ladder).
-/
import Mathlib.Algebra.Module.ZLattice.Basic
import Mathlib.LinearAlgebra.Dimension.OrzechProperty
import Mathlib.LinearAlgebra.Basis.Submodule
import Mathlib.LinearAlgebra.Complex.FiniteDimensional
import Jacobians.RiemannSurface.PeriodNondegeneracy

namespace Jacobians.RiemannSurface

open scoped Manifold Topology
open scoped ContDiff

noncomputable section

/-! ## Generic ZLattice glue

The ℤ-span of `finrank ℝ E` vectors that ℝ-span `E` is the ℤ-span of an
ℝ-basis, hence discrete and a full ℤ-lattice. -/

section ZLatticeGlue

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The ℤ-span of a family of `finrank ℝ E` vectors that ℝ-spans `E` is
discrete: such a family is an ℝ-basis, and the ℤ-span of an ℝ-basis is
discrete (`ZSpan`). -/
theorem discreteTopology_span_int_of_card_eq_finrank {ι : Type*} [Fintype ι]
    {v : ι → E} (hspan : Submodule.span ℝ (Set.range v) = ⊤)
    (hcard : Fintype.card ι = Module.finrank ℝ E) :
    DiscreteTopology (Submodule.span ℤ (Set.range v)) := by
  have hcoe :
      Set.range ⇑(basisOfTopLeSpanOfCardEqFinrank v hspan.ge hcard)
        = Set.range v :=
    congrArg Set.range (coe_basisOfTopLeSpanOfCardEqFinrank v hspan.ge hcard)
  rw [← hcoe]
  infer_instance

/-- The ℤ-span of a set whose ℝ-span is everything is a full ℤ-lattice as
soon as it is discrete. -/
theorem isZLattice_span_int_of_span_real_eq_top {s : Set E}
    [DiscreteTopology (Submodule.span ℤ s)]
    (hspan : Submodule.span ℝ s = ⊤) :
    IsZLattice ℝ (Submodule.span ℤ s) :=
  ⟨by rw [Submodule.span_span_of_tower (R := ℤ) (S := ℝ), hspan]⟩

/-- The ℤ-span of a family of `finrank ℝ E` vectors that ℝ-spans `E` admits
the family itself as a ℤ-basis (`Basis.restrictScalars` of the induced
ℝ-basis). -/
theorem exists_basis_span_int_of_card_eq_finrank {ι : Type*} [Fintype ι]
    {v : ι → E} (hspan : Submodule.span ℝ (Set.range v) = ⊤)
    (hcard : Fintype.card ι = Module.finrank ℝ E) :
    Nonempty (Module.Basis ι ℤ (Submodule.span ℤ (Set.range v))) := by
  have hcoe :
      Submodule.span ℤ
          (Set.range ⇑(basisOfTopLeSpanOfCardEqFinrank v hspan.ge hcard))
        = Submodule.span ℤ (Set.range v) := by
    rw [coe_basisOfTopLeSpanOfCardEqFinrank]
  exact ⟨((basisOfTopLeSpanOfCardEqFinrank v hspan.ge hcard).restrictScalars
    ℤ).map (LinearEquiv.ofEq _ _ hcoe)⟩

end ZLatticeGlue

variable {X : Type*} [TopologicalSpace X] [T2Space X] [CompactSpace X]
  [ConnectedSpace X] [ChartedSpace ℂ X] [IsManifold 𝓘(ℂ) ω X]

/-! ## The loop-period lattice in coordinates -/

/-- `ℂ^g` has real dimension `2g`. -/
theorem finrank_real_genus_coords :
    Module.finrank ℝ (Fin (genus X) → ℂ) = 2 * genus X := by
  rw [← Module.finrank_mul_finrank ℝ ℂ (Fin (genus X) → ℂ),
    Complex.finrank_real_complex, Module.finrank_pi, Fintype.card_fin]

/-- The coordinate period vector of a closed analytic loop with respect to a
basis `b` of the holomorphic 1-forms: `(∮_γ b i)_i ∈ ℂ^g`. -/
def loopPeriodVec (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (γ : AnalyticLoop X x₀) : Fin (genus X) → ℂ :=
  fun i => canonicalArcIntegral γ.arc (b i)

@[simp]
theorem loopPeriodVec_apply (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (γ : AnalyticLoop X x₀) (i : Fin (genus X)) :
    loopPeriodVec x₀ b γ i = canonicalArcIntegral γ.arc (b i) :=
  rfl

/-- The coordinate period vector is the dual-coordinate image of the loop's
period functional. -/
theorem loopPeriodVec_eq_dualCoord (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (γ : AnalyticLoop X x₀) :
    loopPeriodVec x₀ b γ = b.dualBasis.equivFun (loopPeriodFunctional x₀ γ) := by
  funext i
  rw [Module.Basis.dualBasis_equivFun]
  rfl

/-- **The Forster-model period lattice**: the ℤ-span of the coordinate
period vectors of ALL closed analytic loops based at `x₀` (Forster §21.4 —
no chosen cycle basis enters the definition). -/
def loopPeriodLattice (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X)) :
    Submodule ℤ (Fin (genus X) → ℂ) :=
  Submodule.span ℤ (Set.range (loopPeriodVec x₀ b))

theorem loopPeriodVec_mem_loopPeriodLattice (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (γ : AnalyticLoop X x₀) :
    loopPeriodVec x₀ b γ ∈ loopPeriodLattice x₀ b :=
  Submodule.subset_span ⟨γ, rfl⟩

/-- **Spanning (from the B-3 engine, axiom-free).** The loop-period lattice
ℝ-spans `ℂ^g` — `span_loopPeriodFunctional_eq_top` transported through the
dual coordinate equivalence. -/
theorem span_real_loopPeriodLattice_eq_top (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X)) :
    Submodule.span ℝ
      ((loopPeriodLattice x₀ b : Submodule ℤ (Fin (genus X) → ℂ)) :
        Set (Fin (genus X) → ℂ)) = ⊤ := by
  classical
  set e : (HolomorphicOneForm X →ₗ[ℂ] ℂ) ≃ₗ[ℂ] (Fin (genus X) → ℂ) :=
    b.dualBasis.equivFun with he
  have hrange : Set.range (loopPeriodVec x₀ b)
      = ⇑e '' Set.range (loopPeriodFunctional x₀) := by
    rw [← Set.range_comp]
    exact congrArg Set.range (funext fun γ => loopPeriodVec_eq_dualCoord x₀ b γ)
  rw [loopPeriodLattice, Submodule.span_span_of_tower (R := ℤ) (S := ℝ), hrange,
    show ⇑e = ⇑(e.toLinearMap.restrictScalars ℝ) from rfl,
    ← Submodule.map_span, span_loopPeriodFunctional_eq_top x₀,
    Submodule.map_top, LinearMap.range_eq_top]
  exact fun w => ⟨e.symm w, e.apply_symm_apply w⟩

/-! ## The named hypothesis and the B-4/B-5 headlines -/

/-- **Named hypothesis (B-4 residual: the topological rank count).**
A `Fin (2g)`-indexed family of analytic loops *period-generates* at `(x₀, b)`
if every closed analytic loop's period vector lies in the ℤ-span of the
family's period vectors.

This is the lattice shadow of "`H₁(X, ℤ)` is generated by `2g` loop
classes" — purely topological content (Forster §21.4b / the 4g-gon
dissection), with **no** Hodge-theoretic (R1/R2) input. It is discharged by
the chosen `AX_PeriodCycleBasis` witness in
`Layer3/PeriodLatticeDiscrete.lean`, and is the interface a future
dissection- or branched-cover-construction of homology generators must
satisfy to make the discreteness of the period lattice fully axiom-free. -/
def PeriodGeneratingLoops (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (γs : Fin (2 * genus X) → AnalyticLoop X x₀) : Prop :=
  ∀ δ : AnalyticLoop X x₀, loopPeriodVec x₀ b δ ∈
    Submodule.span ℤ (Set.range fun i => loopPeriodVec x₀ b (γs i))

namespace PeriodGeneratingLoops

variable {x₀ : X} {b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X)}
  {γs : Fin (2 * genus X) → AnalyticLoop X x₀}

/-- Under the named hypothesis, the loop-period lattice is the ℤ-span of the
`2g` generating period vectors. -/
theorem lattice_eq (hgen : PeriodGeneratingLoops x₀ b γs) :
    loopPeriodLattice x₀ b
      = Submodule.span ℤ (Set.range fun i => loopPeriodVec x₀ b (γs i)) := by
  refine le_antisymm (Submodule.span_le.mpr ?_) (Submodule.span_le.mpr ?_)
  · rintro _ ⟨δ, rfl⟩
    exact hgen δ
  · rintro _ ⟨i, rfl⟩
    exact loopPeriodVec_mem_loopPeriodLattice x₀ b (γs i)

/-- Under the named hypothesis, the `2g` generating period vectors ℝ-span
`ℂ^g` (from the B-3 spanning). -/
theorem span_real_eq_top (hgen : PeriodGeneratingLoops x₀ b γs) :
    Submodule.span ℝ (Set.range fun i => loopPeriodVec x₀ b (γs i)) = ⊤ := by
  have h := span_real_loopPeriodLattice_eq_top x₀ b
  rwa [hgen.lattice_eq, Submodule.span_span_of_tower (R := ℤ) (S := ℝ)] at h

/-- **B-4 headline: discreteness of the period lattice.** `2g` period
vectors that ℤ-generate the lattice and ℝ-span the `2g`-real-dimensional
`ℂ^g` form an ℝ-basis, so the lattice is the ℤ-span of an ℝ-basis, hence
discrete. -/
theorem discreteTopology (hgen : PeriodGeneratingLoops x₀ b γs) :
    DiscreteTopology (loopPeriodLattice x₀ b) := by
  rw [hgen.lattice_eq]
  exact discreteTopology_span_int_of_card_eq_finrank hgen.span_real_eq_top
    (by rw [Fintype.card_fin, finrank_real_genus_coords])

/-- **B-5: a `Fin (2g)`-indexed ℤ-basis of the period lattice.** -/
theorem exists_basis (hgen : PeriodGeneratingLoops x₀ b γs) :
    Nonempty (Module.Basis (Fin (2 * genus X)) ℤ (loopPeriodLattice x₀ b)) := by
  rw [hgen.lattice_eq]
  exact exists_basis_span_int_of_card_eq_finrank hgen.span_real_eq_top
    (by rw [Fintype.card_fin, finrank_real_genus_coords])

/-- **B-5: the period lattice has ℤ-rank `2g`.** -/
theorem finrank_eq (hgen : PeriodGeneratingLoops x₀ b γs) :
    Module.finrank ℤ (loopPeriodLattice x₀ b) = 2 * genus X := by
  obtain ⟨bZ⟩ := hgen.exists_basis
  rw [Module.finrank_eq_card_basis bZ, Fintype.card_fin]

end PeriodGeneratingLoops

/-- **B-5 headline: the loop-period lattice is a full ℤ-lattice.** Given
discreteness (B-4, from the named hypothesis), the `IsZLattice` spanning
field is exactly the axiom-free B-3 spanning — no named hypothesis needed
here. -/
theorem isZLattice_loopPeriodLattice (x₀ : X)
    (b : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    [DiscreteTopology (loopPeriodLattice x₀ b)] :
    IsZLattice ℝ (loopPeriodLattice x₀ b) :=
  ⟨span_real_loopPeriodLattice_eq_top x₀ b⟩

end

end Jacobians.RiemannSurface
