/-
# TR-DISC from R2 positivity (TD-lane): period-lattice discreteness without the axiom

The lattice-side closure of the image route (#206/#208): derive **TR-DISC**
— `DiscreteTopology (loopPeriodLattice x₀ b)` — from the boundary-word
comparison datum (`ArcBoundaryWordData`, #203), with NO use of
`AX_PeriodCycleBasis`.

The honest split (and what each half needs):

* **The 2g-family sublattice is discrete UNCONDITIONALLY over the datum**
  (`discreteTopology_familyPeriodLattice_of_arcBoundaryWordData`): the
  Phase-C Siegel pattern, transplanted from `Layer3/Periods.lean` to the
  axiom-free arc level. R2 (Gram positive-definiteness, proven from the
  datum by the Kirov port's Green-positivity engine) makes the A-period
  block invertible; the normalized matrix `τ = B·A⁻¹` is symmetric (R1)
  with `Im τ ≻ 0` (R1+R2, `tau_posDef_of_rbr2`); the `[I | τ]` columns are
  ℝ-linearly independent (`periodColumns_linearIndependent`), and the
  ℂ-automorphism `w ↦ Aᵀ *ᵥ w` carries them exactly onto the `2g` loop
  period vectors. `2g` ℝ-independent vectors in the `2g`-real-dimensional
  `ℂ^g` form an ℝ-basis, so their ℤ-span is discrete (`ZSpan`). Note this
  route consumes **neither** the B-3 nondegeneracy engine **nor** any
  topology input — R1/R2 alone make the family vectors independent.
  As corollaries the family vectors also ℝ-span `ℂ^g`
  (`span_real_familyPeriodVec_eq_top_of_arcBoundaryWordData` — a second,
  B-3-free proof of spanning) and the sublattice is a full ℤ-lattice
  (`isZLattice_familyPeriodLattice_of_arcBoundaryWordData`).

* **Full TR-DISC needs the generation hypothesis**
  (`discreteTopology_of_arcBoundaryWordData`): `loopPeriodLattice` is the
  ℤ-span of the period vectors of ALL loops, so discreteness of the full
  image additionally requires every loop's period vector to lie in the
  ℤ-span of the 2g family's — exactly `PeriodGeneratingLoops` (#196), the
  lattice shadow of "H₁ is generated by 2g loop classes" (#198). That
  input is irreducibly topological; with it, `hgen.lattice_eq` collapses
  the full lattice onto the family sublattice.

Resulting residual stack for `AX_PeriodCycleBasis` on the lattice side:
`{ArcBoundaryWordData datum}` + `{PeriodGeneratingLoops}` — no analytic
gap remains between the boundary-word engines and discreteness.

Circularity guard: everything here is stated over `canonicalArcIntegral`
data (`arcAPeriodMatrix`/`arcBPeriodMatrix`/`loopPeriodVec`) and the
axiom-free Layer-3 matrix engine; `AX_PeriodCycleBasis` is NOT consumed
(kernel-checked via `#print axioms` at review time).
-/
import Jacobians.RiemannSurface.BilinearRelationsBoundaryWord
import Jacobians.RiemannSurface.PeriodDiscreteness

namespace Jacobians.RiemannSurface

open scoped Manifold Topology
open scoped ContDiff ComplexOrder Matrix
open Jacobians.Axioms
open Jacobians.Layer3 (PeriodVector Q col omegaCol conjCol periodColumns
  tau_symmetric_of_rbr1 tau_posDef_of_rbr2 periodColumns_linearIndependent
  periodColumns_card_eq_finrank)

noncomputable section

/-! ## Generic glue: ℤ-spans of ℝ-independent families of full card -/

section Glue

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The ℤ-span of an ℝ-linearly independent family of `finrank ℝ E` vectors
is discrete: such a family is an ℝ-basis
(`basisOfLinearIndependentOfCardEqFinrank'`), and the ℤ-span of an ℝ-basis
is discrete (`ZSpan`). Independent-family counterpart of
`discreteTopology_span_int_of_card_eq_finrank`. -/
theorem discreteTopology_span_int_of_linearIndependent_of_card_eq_finrank
    [FiniteDimensional ℝ E] {ι : Type*} [Fintype ι] {v : ι → E}
    (hli : LinearIndependent ℝ v)
    (hcard : Fintype.card ι = Module.finrank ℝ E) :
    DiscreteTopology (Submodule.span ℤ (Set.range v)) := by
  have hcoe :
      Set.range ⇑(basisOfLinearIndependentOfCardEqFinrank' v hli hcard)
        = Set.range v :=
    congrArg Set.range
      (coe_basisOfLinearIndependentOfCardEqFinrank' v hli hcard)
  rw [← hcoe]
  infer_instance

end Glue

variable {X : Type*} [TopologicalSpace X] [T2Space X] [CompactSpace X]
  [ConnectedSpace X] [ChartedSpace ℂ X] [IsManifold 𝓘(ℂ) ω X] {x₀ : X}

/-! ## Linearity of the arc period vector over a basis combination -/

/-- The A-periods of the basis combination `cω.equivFun.symm c` are
`A *ᵥ c` over the arc-period block (arc-level counterpart of
`Layer3.periodVec_fst_eq_aMulVec`). -/
theorem arcPeriodVec_equivFun_symm_fst
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (c : Fin (genus X) → ℂ) :
    (arcPeriodVec loops (cω.equivFun.symm c)).1
      = arcAPeriodMatrix loops (fun m => cω m) *ᵥ c := by
  funext i
  rw [arcPeriodVec_fst, cω.equivFun_symm_apply, canonicalArcIntegral_sum_smul]
  simp only [Matrix.mulVec, dotProduct, arcAPeriodMatrix_apply]
  exact Finset.sum_congr rfl fun j _ => mul_comm _ _

/-- The B-periods of the basis combination `cω.equivFun.symm c` are
`B *ᵥ c` over the arc-period block. -/
theorem arcPeriodVec_equivFun_symm_snd
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (c : Fin (genus X) → ℂ) :
    (arcPeriodVec loops (cω.equivFun.symm c)).2
      = arcBPeriodMatrix loops (fun m => cω m) *ᵥ c := by
  funext i
  rw [arcPeriodVec_snd, cω.equivFun_symm_apply, canonicalArcIntegral_sum_smul]
  simp only [Matrix.mulVec, dotProduct, arcBPeriodMatrix_apply]
  exact Finset.sum_congr rfl fun j _ => mul_comm _ _

/-- The conjugate arc period vector as the entrywise star of the arc period
vector (pair form). -/
theorem conjArcPeriodVec_eq (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (η : HolomorphicOneForm X) :
    conjArcPeriodVec loops η
      = (star (arcPeriodVec loops η).1, star (arcPeriodVec loops η).2) :=
  rfl

/-! ## The A-period block is invertible (from R2 alone) -/

/-- **A-block normalization (from the Gram positivity).** If the arc-period
Gram form is positive definite, no nonzero coefficient vector kills all
A-periods: `A *ᵥ c = 0 → c = 0` (arc-level counterpart of
`Layer3.aPeriodMatrix_mulVec_eq_zero`). -/
theorem arcAPeriodMatrix_mulVec_eq_zero
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef)
    {c : Fin (genus X) → ℂ}
    (h : arcAPeriodMatrix loops (fun m => cω m) *ᵥ c = 0) : c = 0 := by
  by_contra hc
  have hη0 : cω.equivFun.symm c ≠ 0 := by
    rw [Ne, LinearEquiv.map_eq_zero_iff]
    exact hc
  have hAfst : (arcPeriodVec loops (cω.equivFun.symm c)).1 = 0 := by
    rw [arcPeriodVec_equivFun_symm_fst, h]
  have hQ : Q (arcPeriodVec loops (cω.equivFun.symm c))
      (conjArcPeriodVec loops (cω.equivFun.symm c)) = 0 := by
    simp only [Q]
    refine Finset.sum_eq_zero fun k _ => ?_
    have h1 : (arcPeriodVec loops (cω.equivFun.symm c)).1 k = 0 :=
      congrFun hAfst k
    have h2 : (conjArcPeriodVec loops (cω.equivFun.symm c)).1 k = 0 := by
      rw [conjArcPeriodVec_fst, h1, star_zero]
    rw [h1, h2]
    ring
  have hpos2 := arc_R2_of_periodGram_posDef loops cω hpos (cω.equivFun.symm c) hη0
  rw [hQ, mul_zero, Complex.zero_re] at hpos2
  exact lt_irrefl 0 hpos2

/-- The arc-level A-period block of a form basis is invertible whenever the
arc-period Gram form is positive definite. -/
theorem arcAPeriodMatrix_isUnit
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    IsUnit (arcAPeriodMatrix loops fun m => cω m) := by
  rw [Matrix.isUnit_iff_isUnit_det, isUnit_iff_ne_zero]
  intro hdet
  obtain ⟨v, hv, hvz⟩ := Matrix.exists_mulVec_eq_zero_iff.mpr hdet
  exact hv (arcAPeriodMatrix_mulVec_eq_zero loops cω hpos hvz)

/-- `A · A⁻¹ = 1` for the (invertible) arc-level A-period block. -/
theorem arcAPeriodMatrix_mul_inv
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    arcAPeriodMatrix loops (fun m => cω m)
        * (arcAPeriodMatrix loops fun m => cω m)⁻¹ = 1 :=
  Matrix.mul_nonsing_inv _
    ((Matrix.isUnit_iff_isUnit_det _).mp (arcAPeriodMatrix_isUnit loops cω hpos))

/-! ## The arc-level normalized period matrix `τ = B·A⁻¹` -/

/-- The arc-level normalized period matrix `τ = B · A⁻¹` (B-periods of the
A-normalized form basis), built from the arc-period blocks alone. -/
def arcTauMatrix (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X)) :
    Matrix (Fin (genus X)) (Fin (genus X)) ℂ :=
  arcBPeriodMatrix loops (fun m => cω m)
    * (arcAPeriodMatrix loops fun m => cω m)⁻¹

/-- The `j`-th arc-normalized holomorphic differential
`ω̂_j = ∑_k (A⁻¹)_{kj} ω_k`, with A-periods `δ_{·j}`. -/
def arcNormalizedForm (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (j : Fin (genus X)) : HolomorphicOneForm X :=
  cω.equivFun.symm fun k => (arcAPeriodMatrix loops fun m => cω m)⁻¹ k j

/-- The A-normalized combination `∑_j c_j ω̂_j = ∑ (A⁻¹ *ᵥ c)_k ω_k`. -/
def arcNormalizedCombo (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (c : Fin (genus X) → ℂ) : HolomorphicOneForm X :=
  cω.equivFun.symm ((arcAPeriodMatrix loops fun m => cω m)⁻¹ *ᵥ c)

private theorem mulVec_col_eq {g : ℕ} (M N : Matrix (Fin g) (Fin g) ℂ)
    (j : Fin g) :
    M *ᵥ (fun k => N k j) = fun i => (M * N) i j := by
  funext i
  simp only [Matrix.mulVec, dotProduct, Matrix.mul_apply]

/-- The arc-normalized differentials realize the engine's `[I | τ]` columns:
`arcPeriodVec loops ω̂_j = col τ j`. -/
theorem arcPeriodVec_normalizedForm
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) (j : Fin (genus X)) :
    arcPeriodVec loops (arcNormalizedForm loops cω j)
      = col (arcTauMatrix loops cω) j := by
  have hfst : (arcPeriodVec loops (arcNormalizedForm loops cω j)).1
      = Pi.single j 1 := by
    rw [arcNormalizedForm, arcPeriodVec_equivFun_symm_fst, mulVec_col_eq,
      arcAPeriodMatrix_mul_inv loops cω hpos]
    funext i
    simp [Matrix.one_apply, Pi.single_apply, eq_comm]
  have hsnd : (arcPeriodVec loops (arcNormalizedForm loops cω j)).2
      = fun i => arcTauMatrix loops cω i j := by
    rw [arcNormalizedForm, arcPeriodVec_equivFun_symm_snd, mulVec_col_eq]
    rfl
  rw [show col (arcTauMatrix loops cω) j
      = (Pi.single j (1 : ℂ), fun i => arcTauMatrix loops cω i j) from rfl]
  exact Prod.ext hfst hsnd

/-- The arc period vector of `∑ c_j ω̂_j` is the engine's
`omegaCol τ c = (c, τ *ᵥ c)`. -/
theorem arcPeriodVec_normalizedCombo
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef)
    (c : Fin (genus X) → ℂ) :
    arcPeriodVec loops (arcNormalizedCombo loops cω c)
      = omegaCol (arcTauMatrix loops cω) c := by
  have hfst : (arcPeriodVec loops (arcNormalizedCombo loops cω c)).1 = c := by
    rw [arcNormalizedCombo, arcPeriodVec_equivFun_symm_fst,
      Matrix.mulVec_mulVec, arcAPeriodMatrix_mul_inv loops cω hpos,
      Matrix.one_mulVec]
  have hsnd : (arcPeriodVec loops (arcNormalizedCombo loops cω c)).2
      = arcTauMatrix loops cω *ᵥ c := by
    rw [arcNormalizedCombo, arcPeriodVec_equivFun_symm_snd,
      Matrix.mulVec_mulVec]
    rfl
  rw [show omegaCol (arcTauMatrix loops cω) c
      = (c, arcTauMatrix loops cω *ᵥ c) from rfl]
  exact Prod.ext hfst hsnd

/-- The conjugate arc period vector of `∑ c_j ω̂_j` is the engine's
`conjCol τ c`. -/
theorem conjArcPeriodVec_normalizedCombo
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef)
    (c : Fin (genus X) → ℂ) :
    conjArcPeriodVec loops (arcNormalizedCombo loops cω c)
      = conjCol (arcTauMatrix loops cω) c := by
  rw [conjArcPeriodVec_eq, arcPeriodVec_normalizedCombo loops cω hpos]
  rfl

/-- A nonzero coefficient vector gives a nonzero normalized combination
(`A⁻¹` is injective). -/
theorem arcNormalizedCombo_ne_zero
    (loops : Fin (2 * genus X) → AnalyticLoop X x₀)
    (cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef)
    {c : Fin (genus X) → ℂ} (hc : c ≠ 0) :
    arcNormalizedCombo loops cω c ≠ 0 := by
  rw [arcNormalizedCombo, Ne, LinearEquiv.map_eq_zero_iff]
  intro h0
  refine hc ?_
  have h1 : arcAPeriodMatrix loops (fun m => cω m)
      *ᵥ ((arcAPeriodMatrix loops fun m => cω m)⁻¹ *ᵥ c) = c := by
    rw [Matrix.mulVec_mulVec, arcAPeriodMatrix_mul_inv loops cω hpos,
      Matrix.one_mulVec]
  rw [h0, Matrix.mulVec_zero] at h1
  exact h1.symm

/-! ## The Siegel engine hypotheses from the matrix-level R1/R2 -/

section Engine

variable {loops : Fin (2 * genus X) → AnalyticLoop X x₀}
  {cω : Module.Basis (Fin (genus X)) ℂ (HolomorphicOneForm X)}

/-- **RBR1 on the normalized columns** from the matrix-level block symmetry:
the `[I | τ]` columns are `Q`-isotropic. -/
theorem arcTau_col_isotropic
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) (i j : Fin (genus X)) :
    Q (col (arcTauMatrix loops cω) i) (col (arcTauMatrix loops cω) j) = 0 := by
  have h := arc_R1_of_periodMatrix_symm loops cω hsymm
    (arcNormalizedForm loops cω i) (arcNormalizedForm loops cω j)
  rwa [arcPeriodVec_normalizedForm loops cω hpos,
    arcPeriodVec_normalizedForm loops cω hpos] at h

/-- **RBR2 on the normalized columns** from the Gram positivity: the Hodge
quadratic form is positive on every nonzero coefficient vector. -/
theorem arcTau_quadratic_pos
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef)
    (c : Fin (genus X) → ℂ) (hc : c ≠ 0) :
    0 < (Complex.I * Q (omegaCol (arcTauMatrix loops cω) c)
        (conjCol (arcTauMatrix loops cω) c)).re := by
  have h := arc_R2_of_periodGram_posDef loops cω hpos
    (arcNormalizedCombo loops cω c) (arcNormalizedCombo_ne_zero loops cω hpos hc)
  rwa [arcPeriodVec_normalizedCombo loops cω hpos,
    conjArcPeriodVec_normalizedCombo loops cω hpos] at h

/-- The arc-level normalized period matrix is symmetric (R1). -/
theorem arcTauMatrix_isSymm
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    (arcTauMatrix loops cω).IsSymm :=
  tau_symmetric_of_rbr1 (arcTau_col_isotropic hsymm hpos)

/-- `Im τ` is positive definite for the arc-level normalized period matrix
(R1 + R2). -/
theorem arcTauMatrix_im_posDef
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    ((arcTauMatrix loops cω).map Complex.im).PosDef :=
  tau_posDef_of_rbr2 (arcTau_col_isotropic hsymm hpos)
    (arcTau_quadratic_pos hpos)

/-! ## Transport: `w ↦ Aᵀ *ᵥ w` carries `[I | τ]` columns to period vectors -/

/-- `Aᵀ *ᵥ (I-column i) = ` the period vector of the `i`-th α-loop. -/
theorem mulVecT_periodColumns_inl (i : Fin (genus X)) :
    (arcAPeriodMatrix loops fun m => cω m)ᵀ
        *ᵥ periodColumns (arcTauMatrix loops cω) (Sum.inl i)
      = loopPeriodVec x₀ cω (loops (αEmbed i)) := by
  funext j
  simp only [Matrix.mulVec, dotProduct, Matrix.transpose_apply,
    Jacobians.Layer3.periodColumns_inl, mul_ite, mul_one, mul_zero,
    Finset.sum_ite_eq', Finset.mem_univ, if_true]
  rw [loopPeriodVec_apply, arcAPeriodMatrix_apply]

/-- `Aᵀ *ᵥ (τ-column i) = ` the period vector of the `i`-th β-loop
(via `τ` symmetric and `τ·A = B`). -/
theorem mulVecT_periodColumns_inr
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) (i : Fin (genus X)) :
    (arcAPeriodMatrix loops fun m => cω m)ᵀ
        *ᵥ periodColumns (arcTauMatrix loops cω) (Sum.inr i)
      = loopPeriodVec x₀ cω (loops (βEmbed i)) := by
  have hτA : arcTauMatrix loops cω * arcAPeriodMatrix loops (fun m => cω m)
      = arcBPeriodMatrix loops (fun m => cω m) := by
    rw [arcTauMatrix, Matrix.mul_assoc,
      Matrix.nonsing_inv_mul _
        ((Matrix.isUnit_iff_isUnit_det _).mp (arcAPeriodMatrix_isUnit loops cω hpos)),
      Matrix.mul_one]
  funext j
  have hLHS : ((arcAPeriodMatrix loops fun m => cω m)ᵀ
        *ᵥ periodColumns (arcTauMatrix loops cω) (Sum.inr i)) j
      = ∑ k, arcTauMatrix loops cω i k
          * arcAPeriodMatrix loops (fun m => cω m) k j := by
    simp only [Matrix.mulVec, dotProduct, Matrix.transpose_apply,
      Jacobians.Layer3.periodColumns_inr]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [Matrix.IsSymm.apply (arcTauMatrix_isSymm hsymm hpos) i k, mul_comm]
  rw [hLHS, ← Matrix.mul_apply, hτA, loopPeriodVec_apply, arcBPeriodMatrix_apply]

/-- The loop period vectors of the family are exactly the
`Aᵀ`-transported `[I | τ]` columns (range form). -/
theorem range_loopPeriodVec_eq
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    (Set.range fun k => loopPeriodVec x₀ cω (loops k))
      = Set.range fun s => (arcAPeriodMatrix loops fun m => cω m)ᵀ
          *ᵥ periodColumns (arcTauMatrix loops cω) s := by
  apply Set.Subset.antisymm
  · rintro _ ⟨k, rfl⟩
    by_cases h : (k : ℕ) < genus X
    · have hkeq : αEmbed (X := X) ⟨(k : ℕ), h⟩ = k := Fin.ext rfl
      refine ⟨Sum.inl ⟨(k : ℕ), h⟩, ?_⟩
      show (arcAPeriodMatrix loops fun m => cω m)ᵀ
          *ᵥ periodColumns (arcTauMatrix loops cω) (Sum.inl ⟨(k : ℕ), h⟩)
        = loopPeriodVec x₀ cω (loops k)
      rw [mulVecT_periodColumns_inl, hkeq]
    · have hk2 := k.isLt
      have hkeq : βEmbed (X := X) ⟨(k : ℕ) - genus X, by omega⟩ = k := by
        apply Fin.ext
        simp only [βEmbed]
        omega
      refine ⟨Sum.inr ⟨(k : ℕ) - genus X, by omega⟩, ?_⟩
      change (arcAPeriodMatrix loops fun m => cω m)ᵀ
          *ᵥ periodColumns (arcTauMatrix loops cω)
            (Sum.inr ⟨(k : ℕ) - genus X, by omega⟩)
        = loopPeriodVec x₀ cω (loops k)
      rw [mulVecT_periodColumns_inr hsymm hpos, hkeq]
  · rintro _ ⟨s, rfl⟩
    cases s with
    | inl i => exact ⟨αEmbed i, (mulVecT_periodColumns_inl i).symm⟩
    | inr i => exact ⟨βEmbed i, (mulVecT_periodColumns_inr hsymm hpos i).symm⟩

/-- The transported `[I | τ]` columns are ℝ-linearly independent: the
engine's independence (`Im τ ≻ 0`) composed with the injective
ℂ-automorphism `w ↦ Aᵀ *ᵥ w`. -/
theorem linearIndependent_mulVecT_periodColumns
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    LinearIndependent ℝ (fun s => (arcAPeriodMatrix loops fun m => cω m)ᵀ
        *ᵥ periodColumns (arcTauMatrix loops cω) s) := by
  have hdet : IsUnit ((arcAPeriodMatrix loops fun m => cω m)ᵀ).det := by
    rw [Matrix.det_transpose]
    exact (Matrix.isUnit_iff_isUnit_det _).mp (arcAPeriodMatrix_isUnit loops cω hpos)
  have hker : LinearMap.ker
      (((arcAPeriodMatrix loops fun m => cω m)ᵀ).mulVecLin.restrictScalars ℝ)
        = ⊥ := by
    rw [LinearMap.ker_eq_bot]
    intro u v huv
    have huv' : (arcAPeriodMatrix loops fun m => cω m)ᵀ *ᵥ u
        = (arcAPeriodMatrix loops fun m => cω m)ᵀ *ᵥ v := huv
    have h2 : ((arcAPeriodMatrix loops fun m => cω m)ᵀ)⁻¹
          *ᵥ ((arcAPeriodMatrix loops fun m => cω m)ᵀ *ᵥ u)
        = ((arcAPeriodMatrix loops fun m => cω m)ᵀ)⁻¹
          *ᵥ ((arcAPeriodMatrix loops fun m => cω m)ᵀ *ᵥ v) := by
      rw [huv']
    rwa [Matrix.mulVec_mulVec, Matrix.mulVec_mulVec,
      Matrix.nonsing_inv_mul _ hdet, Matrix.one_mulVec,
      Matrix.one_mulVec] at h2
  exact (periodColumns_linearIndependent (arcTauMatrix_im_posDef hsymm hpos)).map'
    (((arcAPeriodMatrix loops fun m => cω m)ᵀ).mulVecLin.restrictScalars ℝ) hker

/-! ## Headlines -/

/-- **The 2g-family period sublattice is discrete — matrix-hypothesis form.**
From the matrix-level R1 (block symmetry) and R2 (Gram positivity) alone:
the ℤ-span of the `2g` loop period vectors of the family is discrete in
`ℂ^g`. No `AX_PeriodCycleBasis`, no B-3 nondegeneracy, no topology input. -/
theorem discreteTopology_familyPeriodLattice_of_periodMatrix
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    DiscreteTopology (Submodule.span ℤ
      (Set.range fun k => loopPeriodVec x₀ cω (loops k))) := by
  rw [range_loopPeriodVec_eq hsymm hpos]
  exact discreteTopology_span_int_of_linearIndependent_of_card_eq_finrank
    (linearIndependent_mulVecT_periodColumns hsymm hpos)
    (periodColumns_card_eq_finrank (genus X))

/-- **The family period vectors ℝ-span `ℂ^g` — matrix-hypothesis form.**
A second, B-3-free proof of the spanning statement: `2g` ℝ-independent
vectors in the `2g`-real-dimensional `ℂ^g` span it. -/
theorem span_real_familyPeriodVec_eq_top_of_periodMatrix
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef) :
    Submodule.span ℝ
      (Set.range fun k => loopPeriodVec x₀ cω (loops k)) = ⊤ := by
  rw [range_loopPeriodVec_eq hsymm hpos]
  exact (linearIndependent_mulVecT_periodColumns hsymm hpos).span_eq_top_of_card_eq_finrank'
    (periodColumns_card_eq_finrank (genus X))

/-- **TR-DISC — matrix-hypothesis form.** Under the generation hypothesis
(`PeriodGeneratingLoops`, the topology residual), the FULL loop-period
lattice is discrete: `hgen.lattice_eq` collapses it onto the family
sublattice, which is discrete from R1/R2 alone. -/
theorem discreteTopology_of_periodMatrix
    (hsymm : (arcAPeriodMatrix loops fun m => cω m)ᵀ
          * (arcBPeriodMatrix loops fun m => cω m)
        = (arcBPeriodMatrix loops fun m => cω m)ᵀ
          * (arcAPeriodMatrix loops fun m => cω m))
    (hpos : (arcPeriodGram loops fun m => cω m).PosDef)
    (hgen : PeriodGeneratingLoops x₀ cω loops) :
    DiscreteTopology (loopPeriodLattice x₀ cω) := by
  rw [hgen.lattice_eq]
  exact discreteTopology_familyPeriodLattice_of_periodMatrix hsymm hpos

/-! ### Boundary-word datum forms -/

/-- **The 2g-family period sublattice is discrete, UNCONDITIONALLY over the
boundary-word datum** (`ArcBoundaryWordData`, #203): the datum's proven
R1/R2 (Cauchy + Green positivity, Kirov port) feed the Siegel engine. -/
theorem discreteTopology_familyPeriodLattice_of_arcBoundaryWordData
    (D : ArcBoundaryWordData loops cω) :
    DiscreteTopology (Submodule.span ℤ
      (Set.range fun k => loopPeriodVec x₀ cω (loops k))) :=
  discreteTopology_familyPeriodLattice_of_periodMatrix
    D.periodMatrix_symm D.periodGram_posDef

/-- The family period vectors ℝ-span `ℂ^g`, unconditionally over the
boundary-word datum (B-3-free spanning). -/
theorem span_real_familyPeriodVec_eq_top_of_arcBoundaryWordData
    (D : ArcBoundaryWordData loops cω) :
    Submodule.span ℝ
      (Set.range fun k => loopPeriodVec x₀ cω (loops k)) = ⊤ :=
  span_real_familyPeriodVec_eq_top_of_periodMatrix
    D.periodMatrix_symm D.periodGram_posDef

/-- The 2g-family period sublattice is a full ℤ-lattice, unconditionally
over the boundary-word datum. -/
theorem isZLattice_familyPeriodLattice_of_arcBoundaryWordData
    (D : ArcBoundaryWordData loops cω) :
    letI := discreteTopology_familyPeriodLattice_of_arcBoundaryWordData D
    IsZLattice ℝ (Submodule.span ℤ
      (Set.range fun k => loopPeriodVec x₀ cω (loops k))) := by
  letI := discreteTopology_familyPeriodLattice_of_arcBoundaryWordData D
  exact isZLattice_span_int_of_span_real_eq_top
    (span_real_familyPeriodVec_eq_top_of_arcBoundaryWordData D)

/-- **TR-DISC from the boundary-word datum + generation (the TD-lane
headline).** The full loop-period lattice `loopPeriodLattice x₀ cω` — the
ℤ-span of the period vectors of ALL closed analytic loops — is discrete,
given (i) the boundary-word comparison datum (analytic input, R1/R2 proven
by the port engines) and (ii) the generation hypothesis
`PeriodGeneratingLoops` (topological input: every loop's period vector lies
in the ℤ-span of the family's). This is the single hypothesis consumed by
the image route (#208); the residual stack for `AX_PeriodCycleBasis` on the
lattice side is exactly {datum} + {generation}. -/
theorem discreteTopology_of_arcBoundaryWordData
    (D : ArcBoundaryWordData loops cω)
    (hgen : PeriodGeneratingLoops x₀ cω loops) :
    DiscreteTopology (loopPeriodLattice x₀ cω) :=
  discreteTopology_of_periodMatrix D.periodMatrix_symm D.periodGram_posDef hgen

end Engine

end

end Jacobians.RiemannSurface
