/-
# Index-2 kernel generation (TGEN lane, L2 fact 1)

`docs/planning/TGEN_ROUTE.md` rung **L2**, fact (1): the *combinatorial
kernel-generation* step of the hyperelliptic (degree-2, regular) covering
generation argument.

For a degree-2 regular cover the deck group is `ℤ/2`, and the parity
homomorphism `φ : π₁(base) → ℤ/2` sends each branch-point lasso into the
nontrivial coset (`φ (g i) ≠ 1`). The covering-space stabilizer of the
basepoint is exactly `ker φ = π_*(π₁(total))`. This file proves the purely
group-theoretic content: **for an order-2 parity quotient `φ` of a group
generated by a distinguished "odd" element `t` together with an odd family
`g`, `ker φ` is generated by the explicit set**

  `S = {t * t} ∪ {t * g i} ∪ {g i * t⁻¹}`.

No general Reidemeister–Schreier is needed: the degree-2 case collapses to a
single transversal element `t` and an even-word `closure_induction` with the
coset-tracking predicate

  `P x := (φ x = 1 → x ∈ K) ∧ (φ x ≠ 1 → t * x ∈ K)`,

where `K = closure S`. The `mul`/`inv` cases need that `t` normalizes `K`
(`Index2KernelGeneration.t_normalizes`), proved by `closure_induction` over
`S`. The only hypothesis on the quotient is the order-2 fact

  `hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1`

("the product of two odd images is even"), which holds for `ℤ/2` and is all
the argument uses (it implies every element is an involution by `a = b`).
Surjectivity of `φ` is not needed.

Mathlib-only group theory; no axiom, no `sorry`.

## Main results

* `Index2KernelGeneration.closure_kernelGenSet_eq_ker` — `K = ker φ` exactly.
* `Index2KernelGeneration.ker_le_closure` / `closure_le_ker` — the two
  inclusions.
* `Index2KernelGeneration.t_normalizes` — `t` conjugates `K` into `K`.
-/
import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Algebra.Group.Subgroup.Ker
import Mathlib.Tactic.Group

namespace Jacobians.Topology.Index2KernelGeneration

variable {G Q ι : Type*} [Group G] [Group Q]
  {φ : G →* Q} {t : G} {g : ι → G}

/-- The explicit generating set for `ker φ` in the degree-2 case:
`{t * t} ∪ {t * g i} ∪ {g i * t⁻¹}` (indices `i` range over `ι`). The
`t * g i` / `g i * t⁻¹` are the **branch-cut cycles** upstairs; the `t ^ 2`
term is the local ramification meridian. -/
def kernelGenSet (t : G) (g : ι → G) : Set G :=
  {t * t} ∪ (Set.range fun i => t * g i) ∪ (Set.range fun i => g i * t⁻¹)

/-- The candidate kernel subgroup `K = closure S`. -/
def Ksub (t : G) (g : ι → G) : Subgroup G := Subgroup.closure (kernelGenSet t g)

theorem mul_self_mem_K : t * t ∈ Ksub t g := by
  apply Subgroup.subset_closure; left; left; rfl

theorem mul_left_mem_K (i : ι) : t * g i ∈ Ksub t g := by
  apply Subgroup.subset_closure; left; right; exact ⟨i, rfl⟩

theorem mul_right_inv_mem_K (i : ι) : g i * t⁻¹ ∈ Ksub t g := by
  apply Subgroup.subset_closure; right; exact ⟨i, rfl⟩

/-! ### Order-2 consequences of the parity hypothesis -/

/-- The order-2 hypothesis makes every image an involution: `φ x * φ x = 1`. -/
theorem odd2_self (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1) (x : G) :
    φ x * φ x = 1 := by
  by_cases hx : φ x = 1
  · simp [hx]
  · exact hodd2 _ _ hx hx

/-- An image is its own inverse under the order-2 hypothesis. -/
theorem odd2_inv (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1) (x : G) :
    (φ x)⁻¹ = φ x := by
  have h := odd2_self (φ := φ) hodd2 x
  rw [← mul_eq_one_iff_inv_eq]
  exact h

/-! ### `K ≤ ker φ` -/

theorem kernelGenSet_subset_ker (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1)
    (ht : φ t ≠ 1) (hodd : ∀ i, φ (g i) ≠ 1) :
    kernelGenSet t g ⊆ (φ.ker : Set G) := by
  rintro x ((rfl | ⟨i, rfl⟩) | ⟨i, rfl⟩)
  · simp only [SetLike.mem_coe, MonoidHom.mem_ker, map_mul]
    exact odd2_self (φ := φ) hodd2 t
  · simp only [SetLike.mem_coe, MonoidHom.mem_ker, map_mul]
    exact hodd2 _ _ ht (hodd i)
  · simp only [SetLike.mem_coe, MonoidHom.mem_ker, map_mul, map_inv,
      odd2_inv (φ := φ) hodd2 t]
    exact hodd2 _ _ (hodd i) ht

theorem closure_le_ker (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1)
    (ht : φ t ≠ 1) (hodd : ∀ i, φ (g i) ≠ 1) : Ksub t g ≤ φ.ker :=
  (Subgroup.closure_le _).mpr (kernelGenSet_subset_ker hodd2 ht hodd)

/-! ### `t` normalizes `K` -/

/-- `t` conjugates the generators of `K` back into `K`. This is the helper that
makes the coset-tracking predicate close under `mul`/`inv`. -/
theorem t_conj_gen_mem {x : G} (hx : x ∈ kernelGenSet t g) :
    t * x * t⁻¹ ∈ Ksub t g := by
  rcases hx with (rfl | ⟨i, rfl⟩) | ⟨i, rfl⟩
  · -- x = t * t : t (t t) t⁻¹ = t t
    have : t * (t * t) * t⁻¹ = t * t := by group
    rw [this]; exact mul_self_mem_K
  · -- x = t * g i : t (t gi) t⁻¹ = (t t)·(gi t⁻¹)
    have : t * (t * g i) * t⁻¹ = (t * t) * (g i * t⁻¹) := by group
    rw [this]
    exact Subgroup.mul_mem _ mul_self_mem_K (mul_right_inv_mem_K i)
  · -- x = g i * t⁻¹ : t (gi t⁻¹) t⁻¹ = (t gi)·(t t)⁻¹
    have : t * (g i * t⁻¹) * t⁻¹ = (t * g i) * (t * t)⁻¹ := by group
    rw [this]
    exact Subgroup.mul_mem _ (mul_left_mem_K i)
      (Subgroup.inv_mem _ mul_self_mem_K)

/-- `t` normalizes `K`: conjugation by `t` maps `K` into `K`. -/
theorem t_normalizes {k : G} (hk : k ∈ Ksub t g) :
    t * k * t⁻¹ ∈ Ksub t g := by
  induction hk using Subgroup.closure_induction with
  | mem x hx => exact t_conj_gen_mem hx
  | one => simp [(Ksub t g).one_mem]
  | mul a b _ _ ha hb =>
    have : t * (a * b) * t⁻¹ = (t * a * t⁻¹) * (t * b * t⁻¹) := by group
    rw [this]; exact Subgroup.mul_mem _ ha hb
  | inv a _ ha =>
    have : t * a⁻¹ * t⁻¹ = (t * a * t⁻¹)⁻¹ := by group
    rw [this]; exact Subgroup.inv_mem _ ha

/-- `t⁻¹` also normalizes `K` (conjugation by the inverse). -/
theorem t_inv_normalizes {k : G} (hk : k ∈ Ksub t g) :
    t⁻¹ * k * t ∈ Ksub t g := by
  have hsq : (t * t)⁻¹ ∈ Ksub t g := Subgroup.inv_mem _ mul_self_mem_K
  have hconj : t * k * t⁻¹ ∈ Ksub t g := t_normalizes hk
  have heq : t⁻¹ * k * t = (t * t)⁻¹ * (t * k * t⁻¹) * (t * t) := by group
  rw [heq]
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hsq hconj) mul_self_mem_K

/-! ### `ker φ ≤ K` via the coset-tracking predicate -/

/-- The coset-tracking predicate: even elements lie in `K`, odd elements lie in
`K` after left-multiplication by the transversal element `t`. -/
def P (t : G) (g : ι → G) (φ : G →* Q) (x : G) : Prop :=
  (φ x = 1 → x ∈ Ksub t g) ∧ (φ x ≠ 1 → t * x ∈ Ksub t g)

theorem P_one : P t g φ 1 := by
  refine ⟨fun _ => (Ksub t g).one_mem, fun h => ?_⟩
  simp at h

theorem P_t (ht : φ t ≠ 1) : P t g φ t :=
  ⟨fun h => absurd h ht, fun _ => mul_self_mem_K⟩

theorem P_gen (hodd : ∀ i, φ (g i) ≠ 1) (i : ι) : P t g φ (g i) :=
  ⟨fun h => absurd h (hodd i), fun _ => mul_left_mem_K i⟩

theorem P_mul (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1)
    {a b : G} (ha : P t g φ a) (hb : P t g φ b) : P t g φ (a * b) := by
  obtain ⟨haE, haO⟩ := ha
  obtain ⟨hbE, hbO⟩ := hb
  refine ⟨fun hE => ?_, fun hO => ?_⟩
  · -- φ(a*b) = 1 : EE or OO.
    by_cases haφ : φ a = 1
    · -- EE
      have hbφ : φ b = 1 := by
        have : φ a * φ b = 1 := by rw [← map_mul]; exact hE
        rwa [haφ, one_mul] at this
      exact Subgroup.mul_mem _ (haE haφ) (hbE hbφ)
    · -- OO
      have hbφ : φ b ≠ 1 := by
        intro hb1
        rw [map_mul, hb1, mul_one] at hE
        exact haφ hE
      have ka := haO haφ      -- t * a ∈ K
      have kb := hbO hbφ      -- t * b ∈ K
      have hconj : t⁻¹ * (t * a) * t ∈ Ksub t g := t_inv_normalizes ka
      have hsqinv : (t * t)⁻¹ ∈ Ksub t g := Subgroup.inv_mem _ mul_self_mem_K
      have heq : a * b = (t⁻¹ * (t * a) * t) * (t * t)⁻¹ * (t * b) := by group
      rw [heq]
      exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hconj hsqinv) kb
  · -- φ(a*b) ≠ 1 : EO or OE.
    by_cases haφ : φ a = 1
    · -- EO : a even, b odd.
      have hbφ : φ b ≠ 1 := by
        intro hb1
        rw [map_mul, haφ, hb1, mul_one] at hO
        exact hO rfl
      have ka := haE haφ      -- a ∈ K
      have kb := hbO hbφ      -- t * b ∈ K
      have hconj : t * a * t⁻¹ ∈ Ksub t g := t_normalizes ka
      have heq : t * (a * b) = (t * a * t⁻¹) * (t * b) := by group
      rw [heq]
      exact Subgroup.mul_mem _ hconj kb
    · -- OE : a odd, b even.
      have hbφ : φ b = 1 := by
        by_contra hb1
        have : φ (a * b) = 1 := by rw [map_mul]; exact hodd2 _ _ haφ hb1
        exact hO this
      have ka := haO haφ      -- t * a ∈ K
      have kb := hbE hbφ      -- b ∈ K
      have heq : t * (a * b) = (t * a) * b := by group
      rw [heq]
      exact Subgroup.mul_mem _ ka kb

theorem P_inv {a : G} (ha : P t g φ a) : P t g φ a⁻¹ := by
  obtain ⟨haE, haO⟩ := ha
  refine ⟨fun hE => ?_, fun hO => ?_⟩
  · have haφ : φ a = 1 := by rwa [map_inv, inv_eq_one] at hE
    exact Subgroup.inv_mem _ (haE haφ)
  · have haφ : φ a ≠ 1 := by rwa [map_inv, inv_ne_one] at hO
    have ka := haO haφ            -- t * a ∈ K
    have kinv : (t * a)⁻¹ ∈ Ksub t g := Subgroup.inv_mem _ ka
    have hsq : t * t ∈ Ksub t g := mul_self_mem_K
    have hconj : t * (t * a)⁻¹ * t⁻¹ ∈ Ksub t g := t_normalizes kinv
    have heq : t * a⁻¹ = (t * (t * a)⁻¹ * t⁻¹) * (t * t) := by group
    rw [heq]
    exact Subgroup.mul_mem _ hconj hsq

/-- The predicate `P` holds for every element of `G`. -/
theorem P_all (hgen : Subgroup.closure (insert t (Set.range g)) = ⊤)
    (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1) (ht : φ t ≠ 1)
    (hodd : ∀ i, φ (g i) ≠ 1) (x : G) : P t g φ x := by
  have hx : x ∈ Subgroup.closure (insert t (Set.range g)) := hgen ▸ Subgroup.mem_top x
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
    rcases hy with rfl | ⟨i, rfl⟩
    · exact P_t ht
    · exact P_gen hodd i
  | one => exact P_one
  | mul a b _ _ ha hb => exact P_mul hodd2 ha hb
  | inv a _ ha => exact P_inv ha

/-- **`ker φ ≤ K`.** Every even element lies in `K`. -/
theorem ker_le_closure (hgen : Subgroup.closure (insert t (Set.range g)) = ⊤)
    (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1) (ht : φ t ≠ 1)
    (hodd : ∀ i, φ (g i) ≠ 1) : φ.ker ≤ Ksub t g := by
  intro x hx
  exact (P_all hgen hodd2 ht hodd x).1 hx

/-- **Index-2 kernel generation.** For a group `G` generated by a distinguished
"odd" element `t` together with an odd family `g`, with respect to an order-2
parity quotient `φ`, the kernel of `φ` is exactly the subgroup generated by
`{t * t} ∪ {t * g i} ∪ {g i * t⁻¹}`. This is L2 fact (1) for the hyperelliptic
degree-2 cover. -/
theorem closure_kernelGenSet_eq_ker
    (hgen : Subgroup.closure (insert t (Set.range g)) = ⊤)
    (hodd2 : ∀ a b : Q, a ≠ 1 → b ≠ 1 → a * b = 1) (ht : φ t ≠ 1)
    (hodd : ∀ i, φ (g i) ≠ 1) : Ksub t g = φ.ker :=
  le_antisymm (closure_le_ker hodd2 ht hodd) (ker_le_closure hgen hodd2 ht hodd)

end Jacobians.Topology.Index2KernelGeneration
