/-
# B1 — π₁ of the punctured plane is generated by explicit circle lassos

Issue #171 / `docs/planning/B1_GENERATION_ROUTE.md` rung **G5** (headline
assembly), on top of the G3/G4 engine (`CellGeneration`).

**Main result** (`fromPath_mem_of_circleLassos_mem`, set form
`closure_circleLassos_eq_top`): every subgroup of `π₁(ℂ ∖ T, x₀)`
containing the classes of all **circle lassos** — spoke-conjugated
explicit circles `p · (circleInPunctured s z) · p⁻¹` around punctures —
contains every loop class; equivalently the circle-lasso classes generate
`π₁(ℂ ∖ T, x₀)` (plain `Subgroup.closure`).

**Method (circle-ization).**  By the G3/G4 engine it suffices to put each
cell-spoke class in `H`.  Inside an admissible cell `W` (open,
`W ∩ T = {s}`, punctured part a once-punctured plane) a loop is an
integer power of the cell lasso (G2, `fromPath_eq_cellLasso_zpow`); a
**tiny explicit circle** around `s` inside a ball `B(s,r) ⊆ W` has
winding number `1` around `s`, so comparing both against the `ℤ`-iso of
the cell forces the tiny circle to BE the cell generator up to sign
(integer-unit argument).  Pushing forward and absorbing the connecting
paths into the spoke exhibits the cell-spoke class as a power of a
spoked circle lasso.

Mathlib-only mathematical content.
-/
import Jacobians.Topology.CellGeneration
import Jacobians.Topology.CellLassoPower

namespace Jacobians.Topology

open Set Complex

local notation "Qmk" => Path.Homotopic.Quotient.mk

/-- The once-punctured plane is path connected. -/
theorem pathConnectedSpace_puncturedPlane (a : ℂ) :
    PathConnectedSpace {w : ℂ // w ≠ a} := by
  have h : IsPathConnected (({a} : Set ℂ)ᶜ) :=
    (countable_singleton a).isPathConnected_compl_of_one_lt_rank
      (by rw [Complex.rank_real_complex]; exact_mod_cast Nat.one_lt_two)
  rw [isPathConnected_iff_pathConnectedSpace] at h
  exact h

/-- Flattening an admissible cell of the punctured plane to its plain
plane form: removing the punctures and removing the cell's own puncture
agree on the cell. -/
def cellFlatten (T : Finset ℂ) (W : Set ℂ) (s : ℂ) (hsT : s ∈ T)
    (hWT : W ∩ (T : Set ℂ) = {s}) :
    {z : {z : ℂ // z ∉ (T : Set ℂ)} // (z : ℂ) ∈ W}
      ≃ₜ {z : ℂ // z ∈ W ∧ z ≠ s} where
  toFun z := ⟨(z.1 : ℂ), z.2, fun h => z.1.2 (h ▸ Finset.mem_coe.mpr hsT)⟩
  invFun w := ⟨⟨w.1, fun hT => w.2.2 (by
      have hmem : (w : ℂ) ∈ W ∩ (T : Set ℂ) := ⟨w.2.1, hT⟩
      rw [hWT] at hmem
      exact hmem)⟩, w.2.1⟩
  left_inv _ := rfl
  right_inv _ := rfl
  continuous_toFun :=
    (continuous_subtype_val.comp continuous_subtype_val).subtype_mk _
  continuous_invFun :=
    (continuous_subtype_val.subtype_mk _).subtype_mk _

/-- **Circle-ization of a cell-spoke class.**  Every cell-spoke generator
lies in any subgroup containing all spoked circle-lasso classes. -/
private theorem cellSpokes_subset_of_circleLassos_mem (T : Finset ℂ)
    (x₀ : {z : ℂ // z ∉ (T : Set ℂ)})
    (H : Subgroup (FundamentalGroup {z : ℂ // z ∉ (T : Set ℂ)} x₀))
    (hlasso : ∀ (s : ℂ), s ∈ T → ∀ (z : {w : ℂ // w ∉ (T : Set ℂ)})
      (hcirc : ∀ t : unitInterval,
        s + ((z : ℂ) - s) * Complex.exp (twoPiI * (t : ℝ)) ∉ (T : Set ℂ))
      (p : Path x₀ z),
      FundamentalGroup.fromPath (Qmk
        (p.trans ((circleInPunctured s z hcirc).trans p.symm))) ∈ H) :
    CellSpokes T x₀ ⊆ (H : Set _) := by
  classical
  rintro g ⟨s, hsT, W, hWo, hWT, ⟨a, ⟨φ⟩⟩, y, δ, hδW, p, rfl⟩
  -- the puncture lies in the cell; fit a ball around it
  have hsW : s ∈ W := by
    have hmem : s ∈ W ∩ (T : Set ℂ) := by
      rw [hWT]
      exact mem_singleton _
    exact hmem.1
  obtain ⟨r, hr0, hball⟩ := Metric.isOpen_iff.mp hWo s hsW
  -- the tiny circle around `s` of radius `r/2`
  set zc : ℂ := s + ((r/2 : ℝ) : ℂ) with hzcdef
  have hzcsub : zc - s = ((r/2 : ℝ) : ℂ) := by
    rw [hzcdef]
    ring
  have hnorm : ∀ t : unitInterval,
      ‖(zc - s) * Complex.exp (twoPiI * (t : ℝ))‖ = r/2 := by
    intro t
    have hre : (twoPiI * ((t : ℝ) : ℂ)).re = 0 := by
      simp [twoPiI, Complex.mul_re, Complex.mul_im]
    rw [norm_mul, hzcsub, Complex.norm_exp, hre, Real.exp_zero, mul_one,
      Complex.norm_real, Real.norm_eq_abs, abs_of_pos (by linarith)]
  have hcircW : ∀ t : unitInterval,
      s + (zc - s) * Complex.exp (twoPiI * (t : ℝ)) ∈ W := by
    intro t
    apply hball
    rw [Metric.mem_ball, Complex.dist_eq]
    have harg : s + (zc - s) * Complex.exp (twoPiI * (t : ℝ)) - s
        = (zc - s) * Complex.exp (twoPiI * (t : ℝ)) := by
      ring
    rw [harg, hnorm t]
    linarith
  have hcircNe : ∀ t : unitInterval,
      s + (zc - s) * Complex.exp (twoPiI * (t : ℝ)) ≠ s := by
    intro t heq
    have h0 : (zc - s) * Complex.exp (twoPiI * (t : ℝ)) = 0 := by
      have := sub_eq_zero.mpr heq
      rwa [add_sub_cancel_left] at this
    have := hnorm t
    rw [h0, norm_zero] at this
    linarith
  have hmemT : ∀ {w : ℂ}, w ∈ W → w ≠ s → w ∉ (T : Set ℂ) := by
    intro w hwW hws hwT
    apply hws
    have hmem : w ∈ W ∩ (T : Set ℂ) := ⟨hwW, hwT⟩
    rwa [hWT] at hmem
  have hcircT : ∀ t : unitInterval,
      s + (zc - s) * Complex.exp (twoPiI * (t : ℝ)) ∉ (T : Set ℂ) :=
    fun t => hmemT (hcircW t) (hcircNe t)
  -- the circle's basepoint
  have hzcW : zc ∈ W := by
    have h0 := hcircW 0
    simpa using h0
  have hzcNe : zc ≠ s := by
    have h0 := hcircNe 0
    simpa using h0
  set zcX : {z : ℂ // z ∉ (T : Set ℂ)} := ⟨zc, hmemT hzcW hzcNe⟩ with hzcXdef
  have hcirc : ∀ t : unitInterval,
      s + ((zcX : ℂ) - s) * Complex.exp (twoPiI * (t : ℝ)) ∉ (T : Set ℂ) :=
    hcircT
  -- the cell as a subset of the punctured plane, and its presentation
  set A : Set {z : ℂ // z ∉ (T : Set ℂ)} := {z | (z : ℂ) ∈ W} with hAdef
  have hyA : y ∈ A := by
    have h0 := hδW 0
    rw [δ.source] at h0
    exact h0
  set φA : (A : Set _) ≃ₜ {w : ℂ // w ≠ a} :=
    (cellFlatten T W s hsT hWT).trans φ with hφAdef
  -- G2: the loop is a power of the cell lasso
  obtain ⟨n, hn⟩ := fromPath_eq_cellLasso_zpow φA hyA δ hδW
  -- the in-cell points and circle
  set yA : (A : Set _) := ⟨y, hyA⟩ with hyAdef
  set zcA : (A : Set _) := ⟨zcX, hzcW⟩ with hzcAdef
  set cA : Path zcA zcA :=
    { toFun := fun t => ⟨⟨s + ((zcX : ℂ) - s) * Complex.exp (twoPiI * (t : ℝ)),
        hcircT t⟩, hcircW t⟩
      continuous_toFun := by fun_prop
      source' := Subtype.ext (Subtype.ext (by simp [hzcAdef]))
      target' := Subtype.ext (Subtype.ext
        (by simp [hzcAdef, twoPiI, Complex.exp_two_pi_mul_I])) } with hcAdef
  -- a connecting path inside the cell
  haveI hpcP : PathConnectedSpace {w : ℂ // w ≠ a} :=
    pathConnectedSpace_puncturedPlane a
  haveI hpcA : PathConnectedSpace (A : Set _) :=
    pathConnectedSpace_of_homeomorph φA.symm
  obtain ⟨ρ⟩ := PathConnectedSpace.joined yA zcA
  -- the in-cell spoked circle and the cell generator
  set scA := spokedClass ρ cA with hscAdef
  set e := pi1MulEquivOfHomeomorph φA yA with hedef
  set isoA := pi1PuncturedPlaneIntAt a (φA yA) with hisoAdef
  set g₀ := e.symm (FundamentalGroup.fromPath
    (Qmk (circleAround a (φA yA)))) with hg₀def
  set E : FundamentalGroup (A : Set _) yA ≃* Multiplicative ℤ :=
    e.trans isoA.symm with hEdef
  have hEg₀ : E g₀ = Multiplicative.ofAdd 1 := by
    show isoA.symm (e (e.symm _)) = _
    rw [MulEquiv.apply_symm_apply, ← pi1PuncturedPlaneIntAt_ofAdd_one,
      MulEquiv.symm_apply_apply]
  have hEsymm_one : E.symm (Multiplicative.ofAdd 1) = g₀ := by
    rw [← hEg₀, MulEquiv.symm_apply_apply]
  -- the spoked circle is an integer power of the generator
  set m : ℤ := Multiplicative.toAdd (E scA) with hmdef
  have hscA_pow : scA = g₀ ^ m := by
    have h1 : scA = E.symm (Multiplicative.ofAdd m) := by
      rw [hmdef, ofAdd_toAdd, MulEquiv.symm_apply_apply]
    have h2 : Multiplicative.ofAdd m = (Multiplicative.ofAdd (1 : ℤ)) ^ m := by
      rw [← ofAdd_zsmul, smul_eq_mul, mul_one]
    rw [h1, h2, map_zpow, hEsymm_one]
  -- the winding homomorphism around `s` on the cell
  set ιs : C((A : Set _), {w : ℂ // w ≠ s}) :=
    ⟨fun z => ⟨((z : {z : ℂ // z ∉ (T : Set ℂ)}) : ℂ),
      fun h => (z : {z : ℂ // z ∉ (T : Set ℂ)}).2
        (h ▸ Finset.mem_coe.mpr hsT)⟩,
      (continuous_subtype_val.comp continuous_subtype_val).subtype_mk _⟩
    with hιsdef
  set wA : FundamentalGroup (A : Set _) yA →* Multiplicative ℤ :=
    (pi1PuncturedPlaneIntAt s (ιs yA)).symm.toMonoidHom.comp
      (FundamentalGroup.mapOfEq ιs rfl) with hwAdef
  -- the winding of the spoked tiny circle is `1`
  have hwsc : wA scA = Multiplicative.ofAdd 1 := by
    show (pi1PuncturedPlaneIntAt s (ιs yA)).symm
        (FundamentalGroup.mapOfEq ιs rfl (spokedClass ρ cA)) = _
    rw [mapOfEq_spokedClass]
    have hcmap : cA.map ιs.continuous = circleAround s (ιs zcA) := by
      ext t
      rfl
    rw [hcmap, spokedClass_eq_transport,
      ← pi1PuncturedPlaneIntAt_ofAdd_one s (ιs zcA),
      fundamentalGroupMulEquivOfPath_pi1PuncturedPlaneIntAt,
      MulEquiv.symm_apply_apply]
  -- winding forces the exponent to be a unit
  have hunit : m = 1 ∨ m = -1 := by
    have hw : Multiplicative.ofAdd (1 : ℤ)
        = Multiplicative.ofAdd (m * Multiplicative.toAdd (wA g₀)) := by
      have h1 : wA scA = (wA g₀) ^ m := by
        rw [hscA_pow, map_zpow]
      rw [← hwsc, h1]
      conv_lhs => rw [← ofAdd_toAdd (wA g₀)]
      rw [← ofAdd_zsmul, smul_eq_mul]
    have hmu : m * Multiplicative.toAdd (wA g₀) = 1 :=
      (Multiplicative.ofAdd.injective hw).symm
    exact Int.isUnit_iff.mp (IsUnit.of_mul_eq_one _ hmu)
  -- hence the generator is the spoked circle up to sign
  have hg₀_eq : g₀ = scA ^ m := by
    rcases hunit with h | h
    · rw [hscA_pow, h, zpow_one, zpow_one]
    · rw [hscA_pow, h]
      group
  -- push everything into the punctured plane
  have hcell_eq : cellLasso φA hyA
      = (spokedClass (ρ.map (inclusionCM A).continuous)
          (cA.map (inclusionCM A).continuous)) ^ m := by
    show FundamentalGroup.mapOfEq (inclusionCM A) rfl g₀ = _
    rw [hg₀_eq, map_zpow, mapOfEq_spokedClass]
  -- identify the pushed circle with the explicit lasso circle
  have hcX : cA.map (inclusionCM A).continuous
      = circleInPunctured s zcX hcirc := by
    ext t
    rfl
  -- assemble the spoked class
  have hδpow : FundamentalGroup.fromPath (Qmk δ)
      = (spokedClass (ρ.map (inclusionCM A).continuous)
          (circleInPunctured s zcX hcirc)) ^ (m * n) := by
    rw [hn, hcell_eq, hcX]
    exact (zpow_mul _ m n).symm
  have hfinal : spokedClass p δ
      = (spokedClass ((p.trans (ρ.map (inclusionCM A).continuous)))
          (circleInPunctured s zcX hcirc)) ^ (m * n) := by
    calc spokedClass p δ
        = FundamentalGroup.fundamentalGroupMulEquivOfPath p.symm
            ((spokedClass (ρ.map (inclusionCM A).continuous)
              (circleInPunctured s zcX hcirc)) ^ (m * n)) := by
          rw [spokedClass_eq_transport, hδpow]
      _ = (FundamentalGroup.fundamentalGroupMulEquivOfPath p.symm
            (spokedClass (ρ.map (inclusionCM A).continuous)
              (circleInPunctured s zcX hcirc))) ^ (m * n) :=
          map_zpow _ _ _
      _ = (spokedClass ((p.trans (ρ.map (inclusionCM A).continuous)))
            (circleInPunctured s zcX hcirc)) ^ (m * n) := by
          congr 1
          rw [spokedClass_trans]
          exact (spokedClass_eq_transport p _).symm
  rw [SetLike.mem_coe, hfinal]
  exact Subgroup.zpow_mem H
    (hlasso s hsT zcX hcirc (p.trans (ρ.map (inclusionCM A).continuous))) _

/-- **B1 headline (membership form).**  Any subgroup of `π₁(ℂ ∖ T, x₀)`
containing the classes of all spoked circle lassos contains every loop
class. -/
theorem fromPath_mem_of_circleLassos_mem (T : Finset ℂ)
    (x₀ : {z : ℂ // z ∉ (T : Set ℂ)})
    (H : Subgroup (FundamentalGroup {z : ℂ // z ∉ (T : Set ℂ)} x₀))
    (hlasso : ∀ (s : ℂ), s ∈ T → ∀ (z : {w : ℂ // w ∉ (T : Set ℂ)})
      (hcirc : ∀ t : unitInterval,
        s + ((z : ℂ) - s) * Complex.exp (twoPiI * (t : ℝ)) ∉ (T : Set ℂ))
      (p : Path x₀ z),
      FundamentalGroup.fromPath (Qmk
        (p.trans ((circleInPunctured s z hcirc).trans p.symm))) ∈ H)
    (γ : Path x₀ x₀) :
    FundamentalGroup.fromPath (Qmk γ) ∈ H :=
  fromPath_mem_of_cellSpokes_subset T x₀ H
    (cellSpokes_subset_of_circleLassos_mem T x₀ H hlasso) γ

/-- The set of spoked circle-lasso classes. -/
def circleLassos (T : Finset ℂ) (x₀ : {z : ℂ // z ∉ (T : Set ℂ)}) :
    Set (FundamentalGroup {z : ℂ // z ∉ (T : Set ℂ)} x₀) :=
  {g | ∃ (s : ℂ) (_ : s ∈ T) (z : {w : ℂ // w ∉ (T : Set ℂ)})
    (hcirc : ∀ t : unitInterval,
      s + ((z : ℂ) - s) * Complex.exp (twoPiI * (t : ℝ)) ∉ (T : Set ℂ))
    (p : Path x₀ z),
    g = FundamentalGroup.fromPath (Qmk
      (p.trans ((circleInPunctured s z hcirc).trans p.symm)))}

/-- **B1 (generation form).**  The spoked circle-lasso classes generate
`π₁(ℂ ∖ T, x₀)` — plain closure, no normal closure needed: the spokes
already absorb all conjugation. -/
theorem closure_circleLassos_eq_top (T : Finset ℂ)
    (x₀ : {z : ℂ // z ∉ (T : Set ℂ)}) :
    Subgroup.closure (circleLassos T x₀) = ⊤ := by
  rw [Subgroup.eq_top_iff']
  intro g
  obtain ⟨γ, hγ⟩ := Path.Homotopic.Quotient.mk_surjective (FundamentalGroup.toPath g)
  have hg : g = FundamentalGroup.fromPath (Qmk γ) := hγ.symm
  rw [hg]
  refine fromPath_mem_of_circleLassos_mem T x₀ _ ?_ γ
  intro s hs z hcirc p
  exact Subgroup.subset_closure ⟨s, hs, z, hcirc, p, rfl⟩

end Jacobians.Topology
