/-
# π₁ of the punctured plane is ℤ, generated by the circle loop

M1 of the SVK-lite ladder (`docs/planning/SVK_ROUTE.md`): for every `a : ℂ`,
the shifted exponential `expAround a : z ↦ a + exp z` is a quotient covering
map `ℂ → {z : ℂ // z ≠ a}` with deck group `2πiℤ`, so the deck isomorphism of
`Jacobians.Topology.CoveringPi1` computes

  `π₁(ℂ ∖ {a}, a + 1) ≃* Multiplicative ℤ`  (`pi1PuncturedPlaneInt`),

with the generator `1` identified as the explicit unit-circle loop
`t ↦ a + exp (2πit)` around the puncture (`pi1PuncturedPlaneInt_ofAdd_one`).
A version at an arbitrary basepoint is provided (`pi1PuncturedPlaneIntAt`).

This is the base case for the punctured-plane winding/generation program
feeding the slit-sheet discharge of `AX_PeriodCycleBasis`
(`docs/planning/CYCLEBASIS_ALTERNATIVES.md` direction 2b).

Mathlib-only mathematical content. Sorry-free and axiom-free
(beyond the three standard axioms).
-/
import Mathlib
import Jacobians.Topology.CoveringPi1

namespace Jacobians.Topology

open Complex

/-- The two-pi-i period of the complex exponential. -/
noncomputable abbrev twoPiI : ℂ := 2 * (Real.pi : ℂ) * Complex.I

theorem twoPiI_ne_zero : twoPiI ≠ 0 := by
  simp [twoPiI, Real.pi_ne_zero, Complex.I_ne_zero]

/-- `ℤ ≃+ ℤa` for a nonzero complex number `a`. -/
noncomputable def intAddEquivZMultiples {a : ℂ} (ha : a ≠ 0) :
    ℤ ≃+ AddSubgroup.zmultiples a :=
  AddEquiv.ofBijective ((zmultiplesHom ℂ a).codRestrict (AddSubgroup.zmultiples a)
      fun n ↦ AddSubgroup.mem_zmultiples_iff.mpr ⟨n, rfl⟩)
    ⟨fun _ _ hnm ↦ smul_left_injective ℤ ha (congrArg Subtype.val hnm),
      fun b ↦ (AddSubgroup.mem_zmultiples_iff.mp b.2).imp fun _ hk ↦ Subtype.ext hk⟩

@[simp] theorem intAddEquivZMultiples_apply_coe {a : ℂ} (ha : a ≠ 0) (n : ℤ) :
    (intAddEquivZMultiples ha n : ℂ) = n • a := rfl

/-- The shifted exponential `z ↦ a + exp z`, covering the plane punctured at `a`. -/
noncomputable def expAround (a : ℂ) (z : ℂ) : {w : ℂ // w ≠ a} :=
  ⟨a + Complex.exp z, by simp [Complex.exp_ne_zero]⟩

@[simp] theorem expAround_coe (a z : ℂ) : (expAround a z : ℂ) = a + Complex.exp z := rfl

theorem continuous_expAround (a : ℂ) : Continuous (expAround a) :=
  (continuous_const.add Complex.continuous_exp).subtype_mk _

theorem expAround_surjective (a : ℂ) : Function.Surjective (expAround a) := fun z ↦
  ⟨Complex.log (z.1 - a), Subtype.ext (by
    simp [Complex.exp_log (sub_ne_zero.mpr z.2)])⟩

/-- Translation by `a` as a homeomorphism from the plane punctured at `0` to the
plane punctured at `a`. -/
noncomputable def addLeftPuncturedHomeo (a : ℂ) : {z : ℂ // z ≠ 0} ≃ₜ {z : ℂ // z ≠ a} where
  toFun w := ⟨a + w.1, by simpa using w.2⟩
  invFun z := ⟨z.1 - a, sub_ne_zero.mpr z.2⟩
  left_inv w := Subtype.ext (by ring)
  right_inv z := Subtype.ext (by ring)
  continuous_toFun := (continuous_const.add continuous_subtype_val).subtype_mk _
  continuous_invFun := (continuous_subtype_val.sub continuous_const).subtype_mk _

/-- `expAround a` is a quotient covering map with deck group `2πiℤ`. -/
theorem isAddQuotientCoveringMap_expAround (a : ℂ) :
    IsAddQuotientCoveringMap (expAround a) (AddSubgroup.zmultiples twoPiI) :=
  Complex.isAddQuotientCoveringMap_exp.homeomorph_comp (addLeftPuncturedHomeo a)

/-- **π₁ of the punctured plane is the deck group `2πiℤ`**, at the basepoint
`expAround a e₀ = a + exp e₀`. -/
noncomputable def pi1PuncturedPlane (a : ℂ) (e₀ : ℂ) :
    Multiplicative (AddSubgroup.zmultiples twoPiI)
      ≃* FundamentalGroup {z : ℂ // z ≠ a} (expAround a e₀) :=
  deckMulEquivPi1 (isAddQuotientCoveringMap_expAround a) e₀

/-- **M1: π₁ of the punctured plane is ℤ** at the basepoint `a + exp e₀`. -/
noncomputable def pi1PuncturedPlaneInt (a : ℂ) (e₀ : ℂ) :
    Multiplicative ℤ ≃* FundamentalGroup {z : ℂ // z ≠ a} (expAround a e₀) :=
  (AddEquiv.toMultiplicative (intAddEquivZMultiples twoPiI_ne_zero)).trans
    (pi1PuncturedPlane a e₀)

/-- The unit-circle loop around the puncture `a`, based at `a + 1`:
`t ↦ a + exp (2πit)`. -/
noncomputable def circleLoop (a : ℂ) : Path (expAround a 0) (expAround a 0) where
  toFun t := expAround a (twoPiI * (t : ℝ))
  continuous_toFun := by
    exact (continuous_expAround a).comp
      (continuous_const.mul (Complex.continuous_ofReal.comp continuous_subtype_val))
  source' := by simp
  target' := by
    apply Subtype.ext
    simp [Complex.exp_two_pi_mul_I, twoPiI]

/-- **Generator identification**: under `pi1PuncturedPlaneInt`, the integer `1`
corresponds to the homotopy class of the unit-circle loop around the puncture. -/
theorem pi1PuncturedPlaneInt_ofAdd_one (a : ℂ) :
    pi1PuncturedPlaneInt a 0 (Multiplicative.ofAdd 1)
      = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (circleLoop a)) := by
  have h1 : pi1PuncturedPlaneInt a 0 (Multiplicative.ofAdd 1)
      = pi1PuncturedPlane a 0
          (Multiplicative.ofAdd (intAddEquivZMultiples twoPiI_ne_zero 1)) := rfl
  rw [h1]
  refine deckMulEquivPi1_eq_fromPath (isAddQuotientCoveringMap_expAround a) 0
    (intAddEquivZMultiples twoPiI_ne_zero 1)
    ⟨⟨fun t ↦ twoPiI * (t : ℝ), by fun_prop⟩, by simp, rfl⟩
    (circleLoop a) (fun t ↦ rfl) ?_
  change twoPiI * ((1 : unitInterval) : ℝ) = intAddEquivZMultiples twoPiI_ne_zero 1 +ᵥ (0 : ℂ)
  rw [AddSubgroup.vadd_def, vadd_eq_add, add_zero]
  simp

/-- π₁ of the punctured plane is ℤ at a basepoint `z` presented as `expAround a e₀`.
The explicit lift basepoint `e₀` makes the generator computation
(`pi1PuncturedPlaneIntOn_eq_fromPath`) cast-free. -/
noncomputable def pi1PuncturedPlaneIntOn (a e₀ : ℂ) (z : {w : ℂ // w ≠ a})
    (hz : expAround a e₀ = z) :
    Multiplicative ℤ ≃* FundamentalGroup {w : ℂ // w ≠ a} z :=
  hz ▸ pi1PuncturedPlaneInt a e₀

/-- **Generator-power identification at any presented basepoint.** If the loop `γ` at
`z = expAround a e₀` lifts pointwise through `expAround a` to a path from `e₀` to
`n • 2πi + e₀`, then `γ` represents the image of `n : ℤ`. -/
theorem pi1PuncturedPlaneIntOn_eq_fromPath (a e₀ : ℂ) (z : {w : ℂ // w ≠ a})
    (hz : expAround a e₀ = z) (n : ℤ) (γ : Path z z)
    (Γ : Path e₀ (n • twoPiI + e₀)) (hΓ : ∀ t, expAround a (Γ t) = γ t) :
    pi1PuncturedPlaneIntOn a e₀ z hz (Multiplicative.ofAdd n)
      = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ) := by
  subst hz
  change pi1PuncturedPlane a e₀
      (Multiplicative.ofAdd (intAddEquivZMultiples twoPiI_ne_zero n))
    = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ)
  refine deckMulEquivPi1_eq_fromPath (isAddQuotientCoveringMap_expAround a) e₀
    (intAddEquivZMultiples twoPiI_ne_zero n) Γ γ hΓ ?_
  rw [AddSubgroup.vadd_def, vadd_eq_add]
  rfl

/-- The standard generator loop at `expAround a e₀`: `t ↦ a + exp e₀ · exp (2πit)`,
the circle of radius `|exp e₀|` around the puncture. -/
noncomputable def circleLoopOn (a e₀ : ℂ) : Path (expAround a e₀) (expAround a e₀) where
  toFun t := expAround a (twoPiI * (t : ℝ) + e₀)
  continuous_toFun := by
    exact (continuous_expAround a).comp
      ((continuous_const.mul (Complex.continuous_ofReal.comp
        continuous_subtype_val)).add continuous_const)
  source' := by simp
  target' := by
    apply Subtype.ext
    simp [Complex.exp_add, Complex.exp_two_pi_mul_I, twoPiI]

theorem pi1PuncturedPlaneIntOn_ofAdd_one (a e₀ : ℂ) (z : {w : ℂ // w ≠ a})
    (hz : expAround a e₀ = z) :
    pi1PuncturedPlaneIntOn a e₀ z hz (Multiplicative.ofAdd 1)
      = FundamentalGroup.fromPath
          (Path.Homotopic.Quotient.mk ((circleLoopOn a e₀).cast hz.symm hz.symm)) := by
  refine pi1PuncturedPlaneIntOn_eq_fromPath a e₀ z hz 1 _
    ⟨⟨fun t ↦ twoPiI * (t : ℝ) + e₀, by fun_prop⟩, by simp, by simp⟩ fun t ↦ rfl

/-- The iso `pi1PuncturedPlaneIntOn` does not depend on the choice of lift basepoint
`e₀` presenting the same basepoint `z`: both send `1 : ℤ` to the same circle-loop
class. -/
theorem pi1PuncturedPlaneIntOn_indep (a e₀ e₀' : ℂ) (z : {w : ℂ // w ≠ a})
    (hz : expAround a e₀ = z) (hz' : expAround a e₀' = z) :
    pi1PuncturedPlaneIntOn a e₀ z hz = pi1PuncturedPlaneIntOn a e₀' z hz' := by
  have hexp : Complex.exp e₀ = Complex.exp e₀' := by
    have := hz.trans hz'.symm
    simpa [expAround, Subtype.ext_iff] using this
  have hloop : (circleLoopOn a e₀).cast hz.symm hz.symm
      = (circleLoopOn a e₀').cast hz'.symm hz'.symm := by
    ext t
    change (expAround a (twoPiI * (t : ℝ) + e₀) : ℂ) = expAround a (twoPiI * (t : ℝ) + e₀')
    simp [Complex.exp_add, hexp]
  apply MulEquiv.toMonoidHom_injective
  apply MonoidHom.ext_mint
  change pi1PuncturedPlaneIntOn a e₀ z hz (Multiplicative.ofAdd 1)
    = pi1PuncturedPlaneIntOn a e₀' z hz' (Multiplicative.ofAdd 1)
  rw [pi1PuncturedPlaneIntOn_ofAdd_one, pi1PuncturedPlaneIntOn_ofAdd_one, hloop]

/-- π₁ of the punctured plane is ℤ at ANY basepoint `z ≠ a`. -/
noncomputable def pi1PuncturedPlaneIntAt (a : ℂ) (z : {w : ℂ // w ≠ a}) :
    Multiplicative ℤ ≃* FundamentalGroup {w : ℂ // w ≠ a} z :=
  pi1PuncturedPlaneIntOn a (Complex.log (z.1 - a)) z
    (Subtype.ext (by simp [Complex.exp_log (sub_ne_zero.mpr z.2)]))

/-- `pi1PuncturedPlaneIntAt` agrees with `pi1PuncturedPlaneIntOn` for any presentation
of the basepoint. -/
theorem pi1PuncturedPlaneIntAt_eq_intOn (a e₀ : ℂ) (z : {w : ℂ // w ≠ a})
    (hz : expAround a e₀ = z) :
    pi1PuncturedPlaneIntAt a z = pi1PuncturedPlaneIntOn a e₀ z hz :=
  pi1PuncturedPlaneIntOn_indep a _ e₀ z _ hz

end Jacobians.Topology
