name = "Jacobians"
version = "0.1.0"
keywords = ["math", "riemann-surfaces", "jacobians"]
defaultTargets = ["Jacobians"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8e3c989104daaa052921bf43de9eef0e1ac9fbf5"

[[lean_lib]]
name = "Jacobians"
