/-
# Albanese discharge interface — the minimal new-axiom layer for G2/G3/G4

The Albanese categoricity capstone `ofCurve_isJacobian` rested on three torus
axioms (`AX_torus_self_albanese` / `AX_period_functoriality` /
`AX_curve_generates_jacobian`). This file replaces them with a **smaller, cleaner,
vetted interface** from which all three are proved as theorems:

* **A1 — `AX_torus_uniformization`** : the single irreducible classical input —
  uniformization of a compact connected complex Lie group (`A ≅ ℂ^m/Λ`,
  Birkenhake–Lange Ch.1). G2 (`torus_self_albanese`) is exactly this; G3
  (`period_functoriality`) follows from it + the already-proven line-integral
  naturality.
* **AK — `AX_curve_image_subgroup_isOpen`** : a **Kirov-interface** axiom (to be
  discharged by vendoring `JacobiLocalMap.lean`, sorry-free). It states the
  content of *local Jacobi inversion* (Forster 21.3 determinant + IFT): the
  Abel–Jacobi image generates a subgroup with non-empty interior. From it G4
  (`curve_generates_jacobian`) follows by "open subgroup of a connected group is
  everything".

See `docs/planning/UNIFIED_ALBANESE_DISCHARGE_PLAN.md`. The complex-subtorus
structure axiom considered earlier is **not** needed — the Kirov local-Jacobi
route avoids it.
-/
import Jacobians.Axioms.TorusAlbanese

noncomputable section

namespace Jacobians.Axioms

open scoped Manifold Topology ContDiff

/-! ## A1 — torus uniformization (the one irreducible new axiom) -/

/-- **A1 (axiom).** Uniformization of a complex torus: a compact connected complex
Lie group modelled on `ℂ^m` is biholomorphically group-isomorphic to `ℂ^m/Λ` for a
full `ZLattice Λ`, and that isomorphism's coordinate is recovered by integrating
the invariant one-forms from `0` (the self-Albanese identity). Packaged as the
`TorusSelfAlbanesePresentation` the universal property consumes.

Reference: Birkenhake–Lange, *Complex Abelian Varieties*, Ch. 1 (every compact
complex Lie group is `ℂ^m/Λ`); Griffiths–Harris Ch. 2. Classical and standard;
off the Buzzard critical path.

Strategy (for eventual discharge): the complex `exp` / developing map of the flat
compact complex Lie group `A` is a surjective group hom `ℂ^m → A` (compact +
connected) whose kernel is a full lattice; invariant forms lift to the constant
cover differentials, so integrating them gives the cover coordinate.

Status: **OUT of every headline closure** (2026-06-14 escape hatch) — declared but NOT
relied on by `ofCurve_isJacobian` / `isJacobian_unique` / `isJacobian_iso_jacobian`, and
registered with NO global instance. Satisfiable / non-vacuous (witness `ℂ^m/Λ` itself; the
underlying mod-Λ `liftCoord_eq_albanese` field was Gemini 3.1-pro re-vetted 2026-06-14). The
*minimal* abstract-supplier boundary `AX_torus_exp` (the planned thinner axiom,
`docs/planning/A1_THINNING_PLAN.md`) is the deep-think-vetted one; this full-presentation form
is kept only as the placeholder supplier until that lands. -/
axiom AX_torus_uniformization {m : ℕ} {A : Type*} [TopologicalSpace A] [T2Space A]
    [CompactSpace A] [ConnectedSpace A] [ChartedSpace (Fin m → ℂ) A] [AddGroup A]
    [IsManifold 𝓘(ℂ, Fin m → ℂ) ω A] [LieAddGroup 𝓘(ℂ, Fin m → ℂ) ω A] :
    TorusSelfAlbanesePresentation m A

/-! ## AK — Kirov local-Jacobi-inversion interface (to be discharged by vendoring) -/

/-- **AK (interface axiom, to be discharged by vendoring Kirov `JacobiLocalMap`).**
The Abel–Jacobi image of a positive-genus curve generates a subgroup of the
Jacobian with **non-empty interior**.

This is the content of **local Jacobi inversion**: by Forster 21.3 there is a
rank-`g` base-point family at which the period-Jacobian determinant is non-zero,
so the `g`-fold Abel–Jacobi sum map is a local diffeomorphism (inverse function
theorem) and its image — a subset of the group generated by `range (ofCurve x₀)`
— contains an open set. Kirov proves exactly this analytic core, sorry-free, in
`Jacobians/PeriodLattice/JacobiLocalMap.lean`
(`exists_jacobiBasePoints_det_ne_zero`, `jacobiDerivEquiv`).

G4 (`curve_generates_jacobian`) is closed from this in `Jacobians.UniversalProperty`
(it needs the Jacobian's `ChartedSpace`/`LieAddGroup` instances, which synthesize
only in that richer context — the `Axioms` layer is too low). -/
axiom AX_curve_image_subgroup_isOpen {X : Type*} [TopologicalSpace X] [T2Space X]
    [CompactSpace X] [ConnectedSpace X] [ChartedSpace ℂ X]
    [IsManifold 𝓘(ℂ) ω X] (x₀ : X) (h : 0 < Jacobians.RiemannSurface.genus X) :
    ∃ U : Set (_root_.Jacobian X), IsOpen U ∧ U.Nonempty ∧
      U ⊆ (AddSubgroup.closure (Set.range (Jacobian.ofCurve x₀)) : Set (_root_.Jacobian X))

end Jacobians.Axioms
