/-
Copyright (c) 2026 Michael R Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

/-
# Branch-cut covering bridge: `BranchCutGeneratesPi1` from the named topology

Closes the last group-theoretic gap between the proven index-2 Schreier
generation (`Index2KernelGeneration.lean`, **Fact (1)**) and the hyperelliptic
T-GEN residual `BranchCutGeneratesPi1` (`CoveringGeneration.lean`, rung L2).
What remains is purely **topological** and Mathlib-absent; it is isolated here
as a single named hypothesis structure `PunctureFillData`.

## The decomposition (`docs/planning/TGEN_ROUTE.md` rung L2)

For the double cover `π : X = {y² = f(x)} → ℙ¹` branched at the roots `B`, with
ramification fiber `T = π⁻¹ B`:

* **(a) Unbranched cover** `X∖T → ℙ¹∖B` — an honest covering map; Mathlib's
  lifting API (`IsCoveringMap.injective_path_homotopic_map`) gives
  `π_* : π₁(X∖T) ↪ π₁(ℙ¹∖B)` with image `ker φ`, the index-2 parity subgroup.
* **(b) Parity monodromy** `φ : π₁(ℙ¹∖B) → Multiplicative (ZMod 2)`, each
  branch-point lasso odd (`φ (lasso) = ofAdd 1`). D1
  (`normalClosure_isolatingLassos_eq_top`) generates the source; **Fact (1)**
  then gives a Schreier generating set of `ker φ ≅ π₁(X∖T)`.
* **(c) Puncture fill** `j_* : π₁(X∖T) ↠ π₁(X)`, the inclusion-induced
  surjection killing the ramification meridians (van Kampen: glue disks over
  `T`; `z ↦ z²` sends each upstairs meridian to `g₁²` downstairs).

`closure_eq_top_of_surjective` (Fact (1)'s companion) then transports the
Schreier generators through `j_*` onto the branch-cut loops, giving
`BranchCutGeneratesPi1`.

## What is proven vs. named here

`branchCutGeneratesPi1_of_punctureFill` proves `BranchCutGeneratesPi1 S` from a
`PunctureFillData S` — a record bundling exactly the Mathlib-absent topological
content of (a)+(b)+(c) as group-theoretic data: a surjection `j` out of some
`Aᵢ`, a generating set `R` of its source, and the fact that each generator
maps into the branch-cut-loop subgroup. **No axiom, no `sorry`**; the residual
is the (currently un-formalized) construction of a `PunctureFillData`, i.e. the
van Kampen surjection (c) together with the covering identification (a)+(b).

Mathlib + project imports; sorry-free and axiom-free (the three standard
axioms). Depends on no challenge axiom.
-/
import Submission.Jacobians.RiemannSurface.CoveringGeneration
import Submission.Jacobians.Topology.Index2KernelGeneration

namespace Jacobians.RiemannSurface.ProjectiveCurve

open Jacobians.ProjectiveCurve BranchCutSystem
open Jacobians.Topology (closure_eq_top_of_surjective)
open scoped Manifold Topology

variable {H : HyperellipticData} {h : Odd H.f.natDegree}

/-- **The named topological residual for hyperelliptic L2.** Bundles the
group-theoretic shadow of the branched-cover decomposition (a)+(b)+(c): a
group `A` (to be instantiated as `π₁(X∖T)`), a *surjective* homomorphism
`fill : A →* π₁(X)` (the puncture-fill van Kampen surjection `j_*`), a
generating set `gen` of `A` (the Schreier generators of `ker φ`, transported
across the covering identification — Fact (1)), and the matching condition
`gen_maps`: every generator projects into the subgroup generated by the
branch-cut loops.

Constructing a `PunctureFillData S` is *exactly* the remaining Mathlib-absent
topology: the unbranched covering identification `π₁(X∖T) ≅ ker φ` and the
puncture-fill surjection `π₁(X∖T) ↠ π₁(X)`. Everything downstream of it is the
proven group theory of `Index2KernelGeneration.lean`. -/
structure PunctureFillData (S : BranchCutSystem H h) where
  /-- The fundamental group of the punctured curve `X∖T` (abstractly). -/
  A : Type*
  /-- Its group structure. -/
  group : Group A
  /-- The puncture-fill homomorphism `j_* : π₁(X∖T) → π₁(X)`. -/
  fill : A →* FundamentalGroup (HyperellipticOdd H h) S.basePoint
  /-- `j_*` is surjective: filling the punctures only adds relations. -/
  fill_surjective : Function.Surjective fill
  /-- A generating set of `π₁(X∖T)` (the Schreier generators of `ker φ`). -/
  gen : Set A
  /-- They generate. -/
  gen_generates : Subgroup.closure gen = ⊤
  /-- Each generator projects into the branch-cut-loop subgroup downstairs. -/
  gen_maps : ∀ a ∈ gen, fill a ∈
    Subgroup.closure (Set.range fun i : Fin (2 * genus (HyperellipticOdd H h)) =>
      loopToPi1 (S.loop i))

/-- **L2 for the hyperelliptic witness, conditional on the named topology.**
Given a `PunctureFillData S` — the puncture-fill van Kampen surjection together
with a generating set whose images land in the branch-cut-loop subgroup — the
branch-cut loops generate `π₁(HyperellipticOdd H h)`, i.e.
`BranchCutGeneratesPi1 S` holds.

The proof is the proven group-theory bridge `closure_eq_top_of_surjective`
applied to `fill`: a surjection carries generators of the source onto
generators of the target. This reduces the hyperelliptic T-GEN residual to the
single topological task of *constructing* a `PunctureFillData`. -/
theorem branchCutGeneratesPi1_of_punctureFill (S : BranchCutSystem H h)
    (D : PunctureFillData S) : BranchCutGeneratesPi1 S :=
  letI := D.group
  closure_eq_top_of_surjective (q := D.fill) D.fill_surjective
    (R := D.gen) D.gen_generates (L := _) D.gen_maps

/-- **Hyperelliptic T-GEN, conditional on the named topology.** Combining the
conditional L2 bridge with the proven K0 keystone: a `PunctureFillData S`
yields T-GEN (`AnalyticLoopsGenerateH1`) at the system's basepoint, axiom-free.
The only un-formalized input is the construction of `PunctureFillData`. -/
theorem analyticLoopsGenerateH1_of_punctureFill (S : BranchCutSystem H h)
    (D : PunctureFillData S) : AnalyticLoopsGenerateH1 S.basePoint :=
  analyticLoopsGenerateH1_hyperelliptic_of_branchCutGenerate S
    (branchCutGeneratesPi1_of_punctureFill S D)

end Jacobians.RiemannSurface.ProjectiveCurve
