/-
# L2: covering-space generation of π₁ ⟹ T-GEN (TGEN lane, rung L2)

`docs/planning/TGEN_ROUTE.md` rung **L2**: the lifted lassos + filled-puncture
relations generate `π₁(X)`. This is the **last mathematical wall** of the
challenge — every other rung of T-GEN is proven:

* **K0** (`AnalyticPi1Generation.lean`): any π₁-generation statement ⟹ T-GEN.
* **D1** (`IsolatingLasso.lean`): π₁(ℂ∖B) is generated by analytic circle
  lassos (`normalClosure_isolatingLassos_eq_top`).
* **L1** (`Hyperelliptic/CycleLoops.lean`): the √-lift of a base arc through
  the branched cover is analytic (`SqrtArcData`, `exists_sqrtArcData`,
  `HyperellipticAffine.sqMap_covering`).

L2 connects D1's downstairs generators to upstairs π₁ across the finite
branched cover `π : X → ℙ¹`. This file does three things:

1. **Names L2 precisely** as one covering-space generation predicate
   (`CoveringGeneratesPi1`) — the final Mathlib-absent topology fact.
2. **Records the witness-family reduction**: for the hyperelliptic
   `BranchCutSystem`, *if* the `2g` branch-cut analytic loops generate
   `π₁(HyperellipticOdd H h)`, *then* T-GEN holds for that curve. This is a
   drop-in over K0's finite-family form — axiom-free, sorry-free. It
   reduces the hyperelliptic instance of T-GEN to a single, concrete
   group-generation hypothesis about explicit loops.
3. **Names the residual** `BranchCutGeneratesPi1` capturing exactly that
   hypothesis, so the wall for the cleanest witness family is one named
   statement, not a mass of covering-space scaffolding.

No new axiom; nothing depends on `AX_PeriodCycleBasis`.

## The precise general L2 wall

> **L2 (general).** Let `π : E → Y` be a finite covering map of
> path-connected, locally path-connected spaces, `e₀ ∈ E`, `S ⊆ π₁(Y, π e₀)`
> a generating set. Then `π₁(E, e₀)` is generated by the set of **closed
> lifts at `e₀`** of those reduced words in `S` whose monodromy fixes `e₀`
> (the Reidemeister–Schreier / point-stabilizer generators). For the
> *branched* completion that fills the finite ramification fiber `T`, the
> meridian classes of `T` are additionally killed (a punctured chart-disk
> upstairs simply-connects after the puncture is filled).

Mathlib supplies more than the genus-1 deck machinery:

* `IsCoveringMap.injective_path_homotopic_map` (Hatcher 1.31) — the covering
  projection `π_*` is **injective** on π₁ (and on every fundamental-groupoid
  Hom-set), so `π₁(E, e₀) ≅ π_*(π₁(E,e₀)) ≤ π₁(Y, π e₀)`.
* `IsCoveringMap.monodromy_bijective` + `monodromy_trans_apply` — the
  monodromy action of `π₁(Y)` on the fiber, with `π_*(π₁(E,e₀))` exactly the
  point-stabilizer of `e₀` (`existsUnique_continuousMap_lifts_of_range_le`,
  the Hatcher-1.33 lifting criterion).
* This project (`CoveringPi1.lean`): `monodromy_injective`/`surjective`,
  `deckMulEquivPi1` for a *simply connected* total space (the genus-1 route).

So the covering side of L2 — `π_*` injective, fiber = cosets, stabilizer
description — is **available**. The two genuinely Mathlib-absent pieces are:

1. **Combinatorial kernel generation.** From a finite generating set
   `g₁,…,gₙ` of `π₁(Y)` and the parity surjection `φ : π₁(Y) → ℤ/2`
   (the degree-2 monodromy; each branch-point lasso has `φ(gᵢ) = 1`), an
   explicit generating set of `ker φ = π_*(π₁(E))`. The index-2 case is
   elementary (no general Reidemeister–Schreier needed): with transversal
   `{1, g₁}`, `ker φ` is generated by
   `{ g₁² } ∪ { g₁ gᵢ, gᵢ g₁⁻¹ : i ≥ 2 }` — proved by induction on words
   with an even letter-count. The `g₁ gᵢ`/`gᵢ g₁⁻¹` lift to the
   **branch-cut cycles** upstairs; `g₁²` lifts to the local ramification
   meridian (killed in step 2).
2. **Branched puncture-filling.** The inclusion `X∖T ↪ X` induces a
   *surjection* `π₁(X∖T) ↠ π₁(X)` with kernel the normal closure of the
   ramification meridians (van Kampen: glue back disks `Dᵢ ⊇` each puncture;
   `π₁(Dᵢ∖0) → π₁(Dᵢ)` kills the meridian). The local model `z ↦ z²`
   sends the upstairs meridian to `g₁²` downstairs, so filling exactly
   quotients the step-1 generators by `gᵢ² = 1`, leaving the branch-cut
   cycles — the classical `2g` generators of `π₁` of the hyperelliptic
   curve.

These two facts together are L2; both are Mathlib-absent and named here as
the residual. The degree-2 (hyperelliptic) instance is strictly more
tractable than general-X because the cover is regular with deck group ℤ/2,
collapsing (1) to the elementary even-word lemma above.
-/
import Submission.Jacobians.RiemannSurface.AnalyticPi1Generation
import Submission.Jacobians.ProjectiveCurve.Hyperelliptic.CycleBasisWitness

namespace Jacobians.RiemannSurface

open scoped Manifold Topology
open scoped ContDiff
open Jacobians.Axioms (loopToHomology loopToPath)
open Jacobians.ProjectiveCurve

noncomputable section

/-! ## The general L2 covering-generation predicate (the named wall) -/

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold 𝓘(ℂ) ω X]

/-- **L2, general form (named residual).** For a basepoint `x₀ : X`, the
property that the analytic-loop classes generate `π₁(X, x₀)` as a group —
i.e. property **(P)** of `TGEN_ROUTE.md`, `pi1AnalyticClasses x₀ = ⊤`.

This is definitionally property (P); naming it here marks the spot where the
covering-space argument (lift D1's downstairs lassos through the branched
cover `π : X → ℙ¹`, fill the ramification punctures) discharges the wall. By
K0 (`analyticLoopsGenerateH1_of_pi1_closure`) it implies T-GEN. -/
def CoveringGeneratesPi1 (x₀ : X) : Prop :=
  pi1AnalyticClasses x₀ = ⊤

/-- **L2 ⟹ T-GEN.** Once the covering-space lift establishes that analytic
loops generate `π₁`, T-GEN follows by the K0 keystone bridge. This is the
exact shape in which a general-X covering argument feeds T-GEN. -/
theorem analyticLoopsGenerateH1_of_coveringGeneratesPi1 {x₀ : X}
    (h : CoveringGeneratesPi1 x₀) : AnalyticLoopsGenerateH1 x₀ :=
  analyticLoopsGenerateH1_of_pi1_closure h

end

/-! ## The hyperelliptic witness: L2 reduced to one generation hypothesis -/

namespace ProjectiveCurve

open Jacobians.ProjectiveCurve BranchCutSystem

variable {H : HyperellipticData} {h : Odd H.f.natDegree}

/-- **L2 for the hyperelliptic witness (named residual).** The `2g`
branch-cut analytic loops of a `BranchCutSystem` generate
`π₁(HyperellipticOdd H h)` at the system's basepoint.

This is the *generation* shadow of the `isBasis`/`tie` hypotheses of
`nonempty_periodCycleBasis_of_branchCutSystem` — strictly weaker (spanning,
not a ℤ-basis), and it is *exactly* what T-GEN needs. Its content is the
double-cover monodromy of `y² = f(x)`: D1's lassos around the branch points
(`normalClosure_isolatingLassos_eq_top`) lift through the √-cover
(`sqMap_covering`, L1) to the system's loops, and these lifts generate π₁
upstairs (the finite-cover stabilizer-generation fact of the general L2
wall, here for an explicit 2-sheeted cover). -/
def BranchCutGeneratesPi1 (S : BranchCutSystem H h) : Prop :=
  Subgroup.closure
      (Set.range fun i : Fin (2 * genus (HyperellipticOdd H h)) =>
        loopToPi1 (S.loop i))
    = ⊤

/-- **T-GEN for the odd hyperelliptic curve, conditional on the named L2
witness.** Given a branch-cut system whose `2g` analytic loops generate π₁
(`BranchCutGeneratesPi1`), the analytic loops ℤ-span `H1` at the system's
basepoint — the named residual **T-GEN** for `HyperellipticOdd H h`.

The proof is the K0 finite-family bridge applied to the explicit
`S.loop : Fin (2g) → AnalyticLoop` family. No axiom, no sorry, no
`AX_PeriodCycleBasis`: the *only* input is the group-generation hypothesis,
which is the hyperelliptic instance of the L2 covering-space wall. This
reduces hyperelliptic T-GEN to one concrete statement about explicit loops. -/
theorem analyticLoopsGenerateH1_hyperelliptic_of_branchCutGenerate
    (S : BranchCutSystem H h) (hgen : BranchCutGeneratesPi1 S) :
    AnalyticLoopsGenerateH1 S.basePoint :=
  analyticLoopsGenerateH1_of_finite_pi1_generators S.loop hgen

end ProjectiveCurve

end Jacobians.RiemannSurface
