/-
# Smooth projective plane curves

A smooth projective plane curve is `X = {[x : y : z] ∈ ℙ² | F(x, y, z) = 0}`
where `F ∈ ℂ[x, y, z]` is a homogeneous polynomial of degree `d ≥ 1`
whose gradient `∇F` has no common zero with `F` on `ℂ³ \ {0}` (smoothness).

**Genus.** For smooth `X` of degree `d ≥ 3`: `g = (d - 1)(d - 2) / 2`
(Plücker formula). For `d = 1` (line) or `d = 2` (conic): `g = 0`, the
curve is biholomorphic to `ℙ¹`.

## Scope of this scaffold

This module defines:
  - `HomogeneousPoly n d`: a homogeneous polynomial of degree `d` in
    `n + 1` variables (polynomial data; no smoothness checks yet).
  - `PlaneCurveData`: the data specifying a smooth plane curve —
    `F` with smoothness + degree hypotheses.
  - `PlaneCurveAffine`: the affine patch `{F(x, y, 1) = 0}` in `ℂ²`.
  - `PlaneCurve`: the compactified projective curve (TODO).

**Full chart construction is not attempted at this pin.** Needs:
  1. Standard affine patches via dehomogenization `[x:y:z] ↦ (x/z, y/z)`
     when `z ≠ 0`, and analogously in the other two patches.
  2. Implicit function theorem: at each smooth point, one of
     `∂F/∂x, ∂F/∂y, ∂F/∂z` is nonzero, so we can locally express `x`
     (or `y`, or `z`) as an analytic function of the others. This gives
     a local chart sending `X` to an open set of `ℂ`.
  3. Chart transitions are polynomial/rational and hence analytic.

## Once complete

Smooth plane curves provide:
  - Concrete genus via Plücker: `g = (d-1)(d-2)/2` — discharges the
    doc-only `AX_PluckerFormula` axiom for this family.
  - Explicit holomorphic differentials: `Ω¹_X` is generated by
    `x^a y^b z^c · (affine form) / (∂F/∂z)` type expressions for
    `a + b + c = d - 3`. Dimension `(d-1)(d-2)/2`, matching the genus.
  - Canonical embedding: for `g ≥ 3`, the canonical map `X → ℙ^{g-1}`
    gives another Track 2 family.

## References

* Griffiths & Harris, *Principles of Algebraic Geometry*, Ch. 2 §2
  (adjunction formula and Plücker).
* Miranda, *Algebraic Curves and Riemann Surfaces*, Ch. III §2
  (smooth projective models).
* Kirwan, *Complex Algebraic Curves*, Ch. 4 (plane curves explicitly).
-/
import Mathlib

namespace Jacobians.ProjectiveCurve

open scoped Manifold Topology
open scoped ContDiff

/-- A homogeneous polynomial of degree `d` in `n + 1` variables over `ℂ`.

At this scaffold pin, stored as a `MvPolynomial (Fin (n + 1)) ℂ` together
with a homogeneity witness. More ergonomic APIs (e.g. projective
subschemes) can be layered later. -/
structure HomogeneousPoly (n d : ℕ) where
  /-- The underlying polynomial in `(Fin (n + 1))`-indexed variables. -/
  val : MvPolynomial (Fin (n + 1)) ℂ
  /-- Homogeneity of degree `d`: every monomial has total degree `d`. -/
  homogeneous : val.IsHomogeneous d

/-- Data specifying a smooth projective plane curve `{F = 0} ⊂ ℙ²`.

We use `n = 2` so the polynomial has three variables `(x, y, z)`. The
smoothness condition (no common zero of `F` and `∇F` on `ℂ³ \ {0}`) is
stored as a separate hypothesis; concrete constructions provide it
directly. -/
structure PlaneCurveData where
  /-- Degree of the defining polynomial, `≥ 1`. -/
  d : ℕ
  h_deg : 1 ≤ d
  /-- The defining homogeneous polynomial `F ∈ ℂ[x, y, z]` of degree `d`. -/
  F : HomogeneousPoly 2 d
  /-- Smoothness: on `ℂ³ \ {0}`, `F = 0` implies some partial derivative
  is nonzero. Ensures the projective vanishing locus is a submanifold. -/
  h_smooth : ∀ v : Fin 3 → ℂ, v ≠ 0 → F.val.eval v = 0 →
    (∃ i : Fin 3, (MvPolynomial.pderiv i F.val).eval v ≠ 0)

namespace PlaneCurveData

/-- The genus of a smooth projective plane curve of degree `d`:
`g = (d - 1)(d - 2) / 2`. Matches the doc-only axiom `AX_PluckerFormula`
once the curve's atlas lands. -/
def genus (H : PlaneCurveData) : ℕ := (H.d - 1) * (H.d - 2) / 2

end PlaneCurveData

/-- **Affine plane curve**: the subtype of `ℂ²` cut out by the
dehomogenization `F(x, y, 1) = 0`.

This is the easy part — a straightforward subtype. The full compact
projective model requires adding the `z = 0` points at infinity and
building charts at each affine/projective patch boundary. -/
def PlaneCurveAffine (H : PlaneCurveData) : Type :=
  { p : ℂ × ℂ // H.F.val.eval ![p.1, p.2, (1 : ℂ)] = 0 }

-- TODO (PlaneCurve): the compactified type
--
--   def PlaneCurve (H : PlaneCurveData) : Type
--
-- obtained from a quotient of `{v ∈ ℂ³ \ {0} | F(v) = 0}` by the
-- `ℂ^× ` scaling action. Requires a full chart atlas derived from the
-- three standard patches `x ≠ 0`, `y ≠ 0`, `z ≠ 0` (projective
-- coordinates), each restricted to the smooth vanishing locus using
-- the implicit function theorem.

-- TODO (instances): seven Buzzard typeclass instances on
-- `PlaneCurve H`. Like `Hyperelliptic`, these do NOT inherit from
-- `ComplexTorus` — each must come from the atlas directly. Shared
-- machinery lives in `Jacobians/ProjectiveCurve/Charts.lean`.

-- TODO (genus_eq): `Jacobians.RiemannSurface.genus (PlaneCurve H) = H.genus`
-- for `H.d ≥ 3` (Plücker). Awaits `OneForm` content at the concrete
-- level.

-- TODO (Pluecker discharge): concrete `AX_PluckerFormula` discharge via
-- the explicit basis of `H^0(Ω¹)` by Poincaré-residue forms
-- `x^a y^b z^c · resF` of homogeneous degree `d - 3`. Dimension
-- `(d-1)(d-2)/2` by counting monomials.

-- TODO (Fermat curves): Fermat curve `{x^d + y^d + z^d = 0}` is a
-- canonical example; would give a concrete family with explicit
-- automorphisms and theta characteristics.

end Jacobians.ProjectiveCurve
