#!/usr/bin/env python3
"""Generate the Centauro blueprint content (`blueprint/src/content.tex`) from the
project's machine-checked structure.

Edges come from `docs/axiom-report.txt` (the golden `#print axioms` of every
headline — machine truth, regenerated by `scripts/axiom_report.lean`); axiom
classification + prose come from the curated tables below (mirroring
`AXIOM_AUDIT.md`). Re-run after discharging an axiom to keep the graph in sync:

    python3 scripts/gen_blueprint.py

A headline theorem is `\\leanok` (its Lean proof is complete) but `\\uses{}` the
axiom nodes it still rests on; an axiom node has no `\\leanok` — it is the work
frontier (a subproject). Discharging an axiom = removing it from the report and
adding `\\leanok` to its node.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPORT = ROOT / "docs" / "axiom-report.txt"
OUT = ROOT / "blueprint" / "src" / "content.tex"

CORE = {"propext", "Classical.choice", "Quot.sound", "sorryAx"}

# The axiom report runs with `open Jacobians`, so it strips the `Jacobians.`
# prefix from dependency names. Restore it so names are the canonical Lean ones
# (verified: every project declaration is `Jacobians.…`).
PROJ_NS = ("Axioms.", "ProjectiveCurve.", "RiemannSurface.", "GeneralResults.",
           "Extensions.", "Bridge.", "Vendor.")


def canon(name):
    if name.startswith("Jacobians."):
        return name
    if name.startswith(PROJ_NS):
        return "Jacobians." + name
    return name  # top-level (genus, Jacobian, ContMDiff.degree, …)

# ----------------------------------------------------------------------------
# Headline declarations: full Lean name -> (label, short title, chapter key).
# Titles/chapters are the curatorial layer; names must match `#print axioms`.
# ----------------------------------------------------------------------------
HEADLINES = {
    # Concrete projective-curve genus theorems (Track 2).
    "Jacobians.ProjectiveCurve.genus_projectiveLine_eq_zero":
        ("thm:genus-P1", r"$\operatorname{genus}\PP^1 = 0$", "genus"),
    "Jacobians.ProjectiveCurve.HolomorphicOneForm_projectiveLine_eq_zero":
        ("thm:forms-P1", r"$\Omega^1(\PP^1) = 0$", "genus"),
    "Jacobians.ProjectiveCurve.genus_Elliptic_eq_one":
        ("thm:genus-E", r"genus of an elliptic curve $= 1$", "genus"),
    "Jacobians.Extensions.HyperellipticEven.genus_HyperellipticEven_eq":
        ("thm:genus-hyp", r"genus of an even hyperelliptic curve $= N/2-1$", "genus"),
    # Buzzard's abstract Jacobian declarations (Track 1).
    "genus": ("def:genus", r"the genus $\dim_{\CC} \Omega^1(X)$", "jac"),
    "Jacobian": ("def:jac", r"the Jacobian $\Omega^1(X)^* / H_1(X;\mathbb{Z})$", "jac"),
    "Jacobian.ofCurve": ("def:aj", r"the Abel--Jacobi map $X \to \operatorname{Jac}(X)$", "jac"),
    "ContMDiff.degree": ("def:deg", r"the degree of a holomorphic map", "jac"),
    "genus_eq_zero_iff_homeo": ("thm:g0", r"genus $0 \iff$ homeomorphic to $\PP^1$", "jac"),
    "Jacobian.ofCurve_self": ("thm:aj-self", r"Abel--Jacobi sends the basepoint to $0$", "jac"),
    "Jacobian.ofCurve_inj": ("thm:aj-inj", r"Abel--Jacobi is injective (genus $>0$)", "jac"),
    "Jacobian.ofCurve_contMDiff": ("thm:aj-smooth", r"Abel--Jacobi is holomorphic", "jac"),
    "Jacobian.pushforward": ("def:push", r"pushforward of $1$-forms / points", "jac"),
    "Jacobian.pullback": ("def:pull", r"pullback of $1$-forms / points", "jac"),
    "Jacobian.pushforward_contMDiff": ("thm:push-smooth", r"pushforward is holomorphic", "jac"),
    "Jacobian.pullback_contMDiff": ("thm:pull-smooth", r"pullback is holomorphic", "jac"),
    "Jacobian.pushforward_id_apply": ("thm:push-id", r"pushforward of the identity", "jac"),
    "Jacobian.pushforward_comp_apply": ("thm:push-comp", r"pushforward is functorial", "jac"),
    "Jacobian.pullback_id_apply": ("thm:pull-id", r"pullback of the identity", "jac"),
    "Jacobian.pullback_comp_apply": ("thm:pull-comp", r"pullback is functorial", "jac"),
    "Jacobian.pushforward_pullback": ("thm:push-pull", r"$\text{push}\circ\text{pull} = \deg$", "jac"),
}
# `Jacobians.Jacobian` and `Jacobian` are the same object; keep the abbrev.
ALIASES = {"Jacobians.Jacobian": "Jacobian"}

CHAPTERS = [
    ("genus", "Concrete genus theorems",
     "Explicit projective-curve models on which the genus is computed directly. "
     "The first three are fully axiom-free; the even hyperelliptic case rests on "
     "the Liouville L2/L3 frontier."),
    ("jac", "The abstract Jacobian (Buzzard's challenge)",
     "Buzzard's 24 target declarations, here proved in Lean modulo the named "
     "axioms below --- the classical Riemann-surface theory each rests on."),
]

# ----------------------------------------------------------------------------
# Axiom frontier: full Lean name -> (class, one-line description from AXIOM_AUDIT).
# Class drives the node section; description is the node prose.
# ----------------------------------------------------------------------------
AX = {
    # Class 1 — textbook-standard (trusted).
    "Axioms.AX_BranchLocus": ("1", "branch-locus / degree finiteness (Miranda Ch. II)"),
    "Axioms.AX_genus_eq_zero_iff_homeo": ("1", "uniformization, genus 0 (Forster §27)"),
    "Axioms.AX_PeriodLattice": ("1", "the period lattice is a full $\\mathbb{Z}$-lattice"),
    "Axioms.instPeriodLatticeDiscrete": ("1", "discreteness of the period lattice (Riemann bilinear)"),
    # Class 2a — data-existence (spec under review).
    "Axioms.pathIntegralBasepointFunctional": ("2a", "the path-integral functional; \\emph{opaque}"),
    "RiemannSurface.loopIntegralToH1": ("2a", "H$_1$-level period descent (multi-chart path integration)"),
    "Axioms.pullbackOneForm": ("2a", "pullback of holomorphic $1$-forms"),
    "Axioms.pushforwardOneForm": ("2a", "trace (pushforward) of holomorphic $1$-forms"),
    "Axioms.localOrder": ("2a", "local multiplicity of a holomorphic map"),
    # Class 2b — definition-asserting (may mask a bad def).
    "Axioms.AX_ofCurve_inj": ("2b", "Abel--Jacobi injectivity; \\emph{opaque-blocked}"),
    "Axioms.AX_ofCurve_contMDiff": ("2b", "Abel--Jacobi smoothness"),
    "Axioms.AX_pushforward_contMDiff": ("2b", "pushforward smoothness"),
    "Axioms.AX_pullback_contMDiff": ("2b", "pullback smoothness"),
    "Axioms.AX_pushforward_pullback": ("2b", "push $\\circ$ pull $=$ degree multiplication"),
    "Axioms.AX_pushforwardAmbient_preserves_lattice": ("2b", "period-map naturality (pushforward)"),
    "Axioms.AX_pullbackAmbient_preserves_lattice": ("2b", "period-map naturality (pullback)"),
    "Axioms.AX_pullbackOneForm_id": ("2b", "pullback preserves identity"),
    "Axioms.AX_pullbackOneForm_comp": ("2b", "pullback is contravariant under composition"),
    "Axioms.AX_pushforwardOneForm_id": ("2b", "trace preserves identity"),
    "Axioms.AX_pushforwardOneForm_comp": ("2b", "trace is covariant under composition"),
    # Class 2c — atlas / structure (curve-specific chart work).
    "Jacobians.ProjectiveCurve.HyperellipticEvenProj.affineLiftChart_compat_infinityLiftChart":
        ("2c", "cross-summand chart compatibility, affine $\\to\\infty$ (SP-1)"),
    "Jacobians.ProjectiveCurve.HyperellipticEvenProj.infinityLiftChart_compat_affineLiftChart":
        ("2c", "cross-summand chart compatibility, $\\infty\\to$ affine (SP-2)"),
    "Jacobians.GeneralResults.contDiffOn_symm_toOpenPartialHomeomorph":
        ("2c", "narrow inverse-function-theorem gap"),
    "Jacobians.ProjectiveCurve.HyperellipticAffine.squareLocalHomeomorph_zero_notMem_source":
        ("2c", "affine-form IFT shape ($\\sqrt{f}$ branch)"),
    "Jacobians.ProjectiveCurve.HyperellipticAffine.polynomialLocalHomeomorph_no_critical_in_source":
        ("2c", "affine-form IFT shape (polynomial branch)"),
    "Jacobians.ProjectiveCurve.HyperellipticAffine.AX_HyperellipticAffine_connected":
        ("2c", "the affine hyperelliptic curve is connected"),
    # Class 2d — flagged (the deepest gaps).
    "Jacobians.Axioms.HyperellipticLiouville.AX_HyperellipticForm_polynomial_decomposition":
        ("2d", "Liouville L2: every holomorphic $1$-form is $g(x)\\,dx/y$, $\\deg g < N/2-1$ (SP-7)"),
    "Jacobians.Axioms.HyperellipticLiouville.AX_HyperellipticOneForm_eq_form":
        ("2d", "Liouville L3: surjectivity onto the low-degree forms (reduces to L2)"),
}
CLASS_TITLES = {
    "1": ("Class 1 --- textbook-standard (trusted)",
          "Standard classical theorems with citations; discharge = port the "
          "textbook proof or import from Mathlib."),
    "2a": ("Class 2a --- data-existence (spec under review)",
           "``This object exists with spec $S$.'' The spec, not the proof, is "
           "the question."),
    "2b": ("Class 2b --- definition-asserting (may mask a bad definition)",
           "``My construction behaves correctly.'' Validate on a concrete witness."),
    "2c": ("Class 2c --- atlas / structure (curve-specific chart work)",
           "Real chart/manifold constructions; classically true, discharge is "
           "substantial chart calculus. These are the prime subprojects."),
    "2d": ("Class 2d --- flagged (the deepest gaps)",
           "True-but-unproven; the classical canonical-differentials theorem for "
           "hyperelliptic curves. The route-D pipeline targets these."),
}


# Canonicalize the curated axiom keys to full `Jacobians.…` names.
AX = {canon(k): v for k, v in AX.items()}


def parse_report():
    txt = REPORT.read_text()
    recs = re.findall(r"'([^']+)' depends on axioms:\s*\[([^\]]*)\]", txt, re.S)
    out = {}
    for name, body in recs:
        name = ALIASES.get(canon(name), canon(name))
        axs = [a.strip() for a in body.replace("\n", " ").split(",")]
        axs = [canon(a) for a in axs if a and a not in CORE]
        out[name] = sorted(set(axs))
    return out


def esc(s):  # already-LaTeX strings pass through; only used for plain text
    return s


def main():
    edges = parse_report()
    # Which axioms are actually referenced (so we only draw live frontier nodes).
    referenced = sorted({a for axs in edges.values() for a in axs})
    lines = []
    w = lines.append

    w("% AUTO-GENERATED by scripts/gen_blueprint.py from docs/axiom-report.txt +")
    w("% the curated tables therein. Do not edit by hand; re-run the generator.\n")

    # Headline chapters.
    for ckey, ctitle, cintro in CHAPTERS:
        w(f"\\chapter{{{ctitle}}}\n")
        w(cintro + "\n")
        for full, (lbl, title, chap) in HEADLINES.items():
            if chap != ckey:
                continue
            axs = edges.get(full, [])
            env = "definition" if lbl.startswith("def:") else "theorem"
            w(f"\\begin{{{env}}}[{title}]")
            w(f"  \\label{{{lbl}}}")
            w(f"  \\lean{{{full}}}")
            w(f"  \\leanok")
            uses = [AX[a][0] and ax_label(a) for a in axs if a in AX]
            uses = [u for u in uses if u]
            if uses:
                w(f"  \\uses{{{','.join(uses)}}}")
            if axs:
                pretty = ", ".join(short(a) for a in axs)
                w(f"  Proved in Lean; rests on: {pretty}.")
            else:
                w(f"  Proved in Lean, \\textbf{{axiom-free}}.")
            w(f"\\end{{{env}}}\n")

    # Axiom frontier chapter, by class.
    w("\\chapter{The axiom frontier}\n")
    w("Every node below is a statement currently taken as an \\texttt{axiom} --- a "
      "staging point to be discharged into a Lean proof (a subproject). Edges into "
      "these nodes are machine-checked (`\\#print axioms`). See "
      "\\texttt{AXIOM\\_AUDIT.md}.\n")
    for cls in ["1", "2a", "2b", "2c", "2d"]:
        members = [a for a in AX if AX[a][0] == cls and (a in referenced or cls in ("2c", "2d"))]
        if not members:
            continue
        ctitle, cintro = CLASS_TITLES[cls]
        w(f"\\section{{{ctitle}}}\n")
        w(cintro + "\n")
        for a in members:
            _, desc = AX[a]
            env = "definition" if a.split(".")[-1][0].islower() and not a.split(".")[-1].startswith("AX") else "lemma"
            w(f"\\begin{{lemma}}[{short(a)}]")
            w(f"  \\label{{{ax_label(a)}}}")
            w(f"  \\lean{{{a}}}")
            w(f"  {desc}.")
            w(f"\\end{{lemma}}\n")

    OUT.write_text("\n".join(lines) + "\n")
    begin = "\\begin"
    nnodes = sum(1 for l in lines if l.startswith(begin))
    print(f"wrote {OUT} : {nnodes} nodes, "
          f"{len(HEADLINES)} headlines, {len(referenced)} referenced axioms")


def short(full):
    return full.split(".")[-1].replace("_", r"\_")


def ax_label(full):
    return "ax:" + full.split(".")[-1].replace("_", "-")


if __name__ == "__main__":
    main()
